import InformationPage from "../../components/InformationPage";
export const metadata = { title: "Términos y Condiciones de Uso | Galletísima" };
export default function Page() { return <InformationPage eyebrow="INFORMACIÓN LEGAL" title="Términos y Condiciones de Uso" intro="¡Bienvenida a Galletisima.cl! Estas condiciones regulan el uso de nuestra tienda online y la compra de nuestros cortadores. Al realizar un pedido, declaras conocer y aceptar estos términos." sections={[
  { title: "1. Información General", paragraphs: ["La propiedad de este sitio web corresponde a Galletísima SpA, con domicilio legal en Santiago, Chile."] },
  { title: "2. Precios y Productos", paragraphs: ["Moneda e IVA: todos los precios están expresados en pesos chilenos ($CLP) e incluyen el IVA correspondiente.", "Fabricación a pedido: cada cortador se fabrica especialmente para ti mediante impresión 3D, proceso que toma entre 3 y 5 días hábiles antes del despacho.", "Fotografías y colores: las imágenes son referenciales. El color del PLA puede variar según disponibilidad, pero la forma, la medida de 0,6 mm de borde y la calidad de corte se mantienen."] },
  { title: "3. Pagos y Boletas o Facturas", paragraphs: ["Aceptamos tarjetas de crédito o débito, transferencia bancaria directa y pago contra entrega, este último exclusivamente en Santiago.", "Por cada compra emitiremos la boleta o factura electrónica correspondiente, que llegará al correo una vez confirmado el pago."] },
  { title: "4. Despachos y Envíos", paragraphs: ["Realizamos envíos a todo Chile mediante Blue Express.", "Al plazo de transporte debes sumar entre 3 y 5 días hábiles de confección. El plazo de Blue Express dependerá de la comuna o región.", "Debes ingresar correctamente la dirección y procurar que alguien reciba el paquete. Si vuelve al taller por un error en la dirección o porque no había quien lo recibiera, el comprador deberá asumir el nuevo despacho."] },
  { title: "5. Uso Responsable y Cuidados del Material", paragraphs: ["Nuestros cortadores están fabricados en PLA (ácido poliláctico), un bioplástico de origen vegetal seguro para alimentos.", "El PLA es sensible a altas temperaturas. Galletísima no se responsabiliza por deformaciones o derretimiento ocasionados por lavavajillas, agua caliente, hornos u otras fuentes de calor. Lava siempre los cortadores a mano y con agua fría."] },
  { title: "6. Garantías y Devoluciones", paragraphs: ["Los cambios, la garantía de 6 meses por fallas de fábrica y el derecho a retracto se rigen por la Ley del Consumidor (Ley 19.496). Los plazos, el reembolso del 50% por retracto y las condiciones de envío se detallan en nuestra Política de Devoluciones y Reembolsos."] },
  { title: "7. Privacidad de Datos", paragraphs: ["Los datos entregados, como nombre, dirección, correo y teléfono, se utilizan exclusivamente para procesar el pedido y solo se comparten con Blue Express cuando es necesario realizar la entrega."] },
  { title: "8. Legislación Aplicable", paragraphs: ["Toda controversia derivada de estas compras se someterá a las leyes de la República de Chile y a la competencia de los tribunales de justicia de la comuna de Santiago."] },
]} />; }
