import InformationPage from "../../components/InformationPage";
export const metadata = { title: "Política de devoluciones y reembolsos | Galletísima" };
export default function Page() { return <InformationPage eyebrow="COMPRAS" title="Nuestra Política de Devoluciones y Reembolsos" intro="En Galletísima ponemos todo nuestro corazón y dedicación en cada cortador que fabricamos. Al ser productos elaborados a pedido especialmente para ti, esta política nos permite seguir entregándote la mejor calidad, cuidando nuestro trabajo y protegiendo siempre tus derechos." sections={[
  { title: "1. Si cambiaste de opinión (Derecho a Retracto)", paragraphs: ["Tienes un plazo de 3 días corridos desde que recibes tu pedido para solicitar una devolución. Al ser productos que requieren tiempo de diseño e impresión 3D exclusiva para ti, el reembolso en estos casos corresponderá al 50% del valor de los productos.", "Condición indispensable: el cortador debe estar nuevo, sin ningún tipo de uso, completo y sin daños."] },
  { title: "2. Garantía Legal (Fallas de Fábrica)", paragraphs: ["Si tu cortador presenta algún defecto de fabricación o un problema de impresión, cuentas con una garantía legal de 6 meses y puedes elegir la reposición o el cambio por un molde nuevo.", "Esta garantía no cubre daños por mal uso, como caídas fuertes o deformaciones causadas por fuentes de calor o lavados con agua caliente. El PLA eco-amigable no resiste altas temperaturas."] },
  { title: "3. Costos de Envío", paragraphs: ["Si la devolución es por retracto, el envío de regreso a nuestro taller es responsabilidad del comprador. Si se envía por pagar, ese costo se descontará del monto de la devolución.", "Si la devolución se debe a una falla de fábrica, Galletísima asumirá todos los costos de envío."] },
  { title: "4. ¿Cómo iniciar el proceso?", paragraphs: ["Escríbenos por WhatsApp o correo electrónico con tu número de pedido y fotografías que muestren el estado del producto. Te guiaremos paso a paso y te entregaremos la dirección para el envío."] },
  { title: "5. Plazos de Reembolso", paragraphs: ["Una vez recibido el producto y comprobado que todo está en orden, procesaremos la devolución.", "Transferencia o débito: depositaremos el dinero en tu cuenta en un plazo máximo de 72 horas hábiles.", "Tarjetas de crédito: gestionaremos la reversa. El dinero suele aparecer entre 5 y 10 días hábiles, según los plazos del banco."] },
]} />; }
