-- Catálogo importado desde Productos_Galletisimacl_20260811.xlsx.
-- Las 6 filas sin SKU/título se omiten. Precio, stock e imagen quedan pendientes.
insert into public.categories (name,slug,description,active) values
('Todo Animales','todo-animales','',true),
('Todo Animalitos','todo-animalitos','',true),
('Todo Anime','todo-anime','',true),
('Todo Baby Shower','todo-baby-shower','',true),
('Todo Bebes','todo-bebes','',true),
('Todo Bluey','todo-bluey','',true),
('Todo Bob Esponja','todo-bob-esponja','',true),
('Todo Capibara','todo-capibara','',true),
('Todo Cartoon','todo-cartoon','',true),
('Todo Celebracion','todo-celebracion','',true),
('Todo Chile','todo-chile','',true),
('Todo Deporte','todo-deporte','',true),
('Todo Disney','todo-disney','',true),
('Todo Fiestas Patrias','todo-fiestas-patrias','',true),
('Todo FoodHall','todo-foodhall','',true),
('Todo Futbol','todo-futbol','',true),
('Todo Gamer','todo-gamer','',true),
('Todo Guerreras Kpop','todo-guerreras-kpop','',true),
('Todo Halloween','todo-halloween','',true),
('Todo Hombre','todo-hombre','',true),
('Todo La Casa de Gabby','todo-la-casa-de-gabby','',true),
('Todo LiLo-Stitch','todo-lilo-stitch','',true),
('Todo Mamá','todo-mama','',true),
('Todo Marinos Cute','todo-marinos-cute','',true),
('Todo Marvel','todo-marvel','',true),
('Todo Miedo','todo-miedo','',true),
('Todo Mujer','todo-mujer','',true),
('Todo Navidad','todo-navidad','',true),
('Todo Netflix','todo-netflix','',true),
('Todo Niños','todo-ninos','',true),
('Todo Papá','todo-papa','',true),
('Todo PawPatrol','todo-pawpatrol','',true),
('Todo Pokemon','todo-pokemon','',true),
('Todo Postres Disney','todo-postres-disney','',true),
('Todo Snoopy','todo-snoopy','',true),
('Todo Spiderman','todo-spiderman','',true),
('Todo Stitch','todo-stitch','',true),
('Todo Superheroes','todo-superheroes','',true),
('Todo ToyStory','todo-toystory','',true),
('Todo Winie The Pooh','todo-winie-the-pooh','',true)
on conflict (slug) do update set name=excluded.name, active=true;

insert into public.products (name,slug,sku,source_group,source_number,description,price,stock,size,image_url,active,featured) values
('Bluey','bluey','SKUbluey001','01_Bluey_FinalWeb','001','',0,0,'','',false,false),
('Bingo','bingo','SKUbingo002','01_Bluey_FinalWeb','002','',0,0,'','',false,false),
('Unicorse','unicorse','SKUunicorse003','01_Bluey_FinalWeb','003','',0,0,'','',false,false),
('B&B','b-b','SKUb&b004','01_Bluey_FinalWeb','004','',0,0,'','',false,false),
('Mom&Dad','mom-dad','SKUmom&dad005','01_Bluey_FinalWeb','005','',0,0,'','',false,false),
('Bluey 2','bluey-2','SKUbluey2006','01_Bluey_FinalWeb','006','',0,0,'','',false,false),
('PomPom','pompom','SKUpompom007','01_Bluey_FinalWeb','007','',0,0,'','',false,false),
('Coco','coco','SKUcoco008','01_Bluey_FinalWeb','008','',0,0,'','',false,false),
('B&B Cartoon','b-b-cartoon','SKUb&bcartoon009','01_Bluey_FinalWeb','009','',0,0,'','',false,false),
('B&B Rainbow','b-b-rainbow','SKUb&brainbow010','01_Bluey_FinalWeb','010','',0,0,'','',false,false),
('Pulpito','pulpito','SKUpulpito001','02_MarinosCute_FinalWeb','001','',0,0,'','',false,false),
('Delfin','delfin','SKUdelfin002','02_MarinosCute_FinalWeb','002','',0,0,'','',false,false),
('Ballenita','ballenita','SKUballenita003','02_MarinosCute_FinalWeb','003','',0,0,'','',false,false),
('Delfin2','delfin2','SKUdelfin2004','02_MarinosCute_FinalWeb','004','',0,0,'','',false,false),
('Tortuguita','tortuguita','SKUtortuguita005','02_MarinosCute_FinalWeb','005','',0,0,'','',false,false),
('Tiburoncin','tiburoncin','SKUtiburoncin006','02_MarinosCute_FinalWeb','006','',0,0,'','',false,false),
('Estrellita','estrellita','SKUestrellita007','02_MarinosCute_FinalWeb','007','',0,0,'','',false,false),
('Lucario','lucario','SKUlucario001','03_Pokemon_FinalWeb','001','',0,0,'','',false,false),
('Squirtle','squirtle','SKUsquirtle002','03_Pokemon_FinalWeb','002','',0,0,'','',false,false),
('Jigglypuff','jigglypuff','SKUjigglypuff003','03_Pokemon_FinalWeb','003','',0,0,'','',false,false),
('Mewtwo','mewtwo','SKUmewtwo004','03_Pokemon_FinalWeb','004','',0,0,'','',false,false),
('Charmander','charmander','SKUcharmander005','03_Pokemon_FinalWeb','005','',0,0,'','',false,false),
('Eevee','eevee','SKUeevee006','03_Pokemon_FinalWeb','006','',0,0,'','',false,false),
('Pikachu 2','pikachu-2','SKUpikachu2007','03_Pokemon_FinalWeb','007','',0,0,'','',false,false),
('Bulbasaur','bulbasaur','SKUbulbasaur008','03_Pokemon_FinalWeb','008','',0,0,'','',false,false),
('Dragonite','dragonite','SKUdragonite009','03_Pokemon_FinalWeb','009','',0,0,'','',false,false),
('Gengar','gengar','SKUgengar010','03_Pokemon_FinalWeb','010','',0,0,'','',false,false),
('Pokeball','pokeball','SKUpokeball011','03_Pokemon_FinalWeb','011','',0,0,'','',false,false),
('Face Squirtle','face-squirtle','SKUfacesquirtle012','03_Pokemon_FinalWeb','012','',0,0,'','',false,false),
('Face Charmander','face-charmander','SKUfacecharmander013','03_Pokemon_FinalWeb','013','',0,0,'','',false,false),
('Face Pikachu','face-pikachu','SKUfacepikachu014','03_Pokemon_FinalWeb','014','',0,0,'','',false,false),
('Face Bulbasaur','face-bulbasaur','SKUfacebulbasaur015','03_Pokemon_FinalWeb','015','',0,0,'','',false,false),
('Pikachu','pikachu','SKUpikachu016','03_Pokemon_FinalWeb','016','',0,0,'','',false,false),
('SpiderFace','spiderface','SKUspiderface001','04_Spiderman_FinalWeb','001','',0,0,'','',false,false),
('SpiderMask','spidermask','SKUspidermask002','04_Spiderman_FinalWeb','002','',0,0,'','',false,false),
('SpiderLogo','spiderlogo','SKUspiderlogo003','04_Spiderman_FinalWeb','003','',0,0,'','',false,false),
('Spiderman Cute','spiderman-cute','SKUspidermancute004','04_Spiderman_FinalWeb','004','',0,0,'','',false,false),
('Spiderman Listo','spiderman-listo','SKUspidermanlisto005','04_Spiderman_FinalWeb','005','',0,0,'','',false,false),
('Spiderman Shibi','spiderman-shibi','SKUspidermanshibi006','04_Spiderman_FinalWeb','006','',0,0,'','',false,false),
('Spidy','spidy','SKUspidy007','04_Spiderman_FinalWeb','007','',0,0,'','',false,false),
('Sentido Aracnido','sentido-aracnido','SKUsentidoaracnido008','04_Spiderman_FinalWeb','008','',0,0,'','',false,false),
('Escudo Cap America','escudo-cap-america','SKUescudocapamerica001','05_Marvel_WebFinal','001','',0,0,'','',false,false),
('Logo Avengers','logo-avengers','SKUlogoavengers003','05_Marvel_WebFinal','003','',0,0,'','',false,false),
('Martillo Thor','martillo-thor','SKUmartillothor004','05_Marvel_WebFinal','004','',0,0,'','',false,false),
('Guantelete','guantelete','SKUguantelete005','05_Marvel_WebFinal','005','',0,0,'','',false,false),
('Puño Hulk','puno-hulk','SKUpuñohulk007','05_Marvel_WebFinal','007','',0,0,'','',false,false),
('Casco Ironman','casco-ironman','SKUcascoironman008','05_Marvel_WebFinal','008','',0,0,'','',false,false),
('Mascara Wolverine','mascara-wolverine','SKUmascarawolverine009','05_Marvel_WebFinal','009','',0,0,'','',false,false),
('Logo DeadPool','logo-deadpool','SKUlogodeadpool010','05_Marvel_WebFinal','010','',0,0,'','',false,false),
('CupCake','cupcake','SKUcupcake001','06_FoodHall_WebFinal','001','',0,0,'','',false,false),
('Queso','queso','SKUqueso002','06_FoodHall_WebFinal','002','',0,0,'','',false,false),
('Malteada','malteada','SKUmalteada003','06_FoodHall_WebFinal','003','',0,0,'','',false,false),
('Sandia','sandia','SKUsandia004','06_FoodHall_WebFinal','004','',0,0,'','',false,false),
('Banana','banana','SKUbanana005','06_FoodHall_WebFinal','005','',0,0,'','',false,false),
('Hamburguesa','hamburguesa','SKUhamburguesa007','06_FoodHall_WebFinal','007','',0,0,'','',false,false),
('Cono Helado','cono-helado','SKUconohelado008','06_FoodHall_WebFinal','008','',0,0,'','',false,false),
('Paleta Helado','paleta-helado','SKUpaletahelado009','06_FoodHall_WebFinal','009','',0,0,'','',false,false),
('Pan Rebanada','pan-rebanada','SKUpanrebanada010','06_FoodHall_WebFinal','010','',0,0,'','',false,false),
('Caramelo','caramelo','SKUcaramelo011','06_FoodHall_WebFinal','011','',0,0,'','',false,false),
('Piruleta','piruleta','SKUpiruleta013','06_FoodHall_WebFinal','013','',0,0,'','',false,false),
('Shop','shop','SKUshop014','06_FoodHall_WebFinal','014','',0,0,'','',false,false),
('Torta','torta','SKUtorta015','06_FoodHall_WebFinal','015','',0,0,'','',false,false),
('Vaso de Jugo','vaso-de-jugo','SKUvasodejugo016','06_FoodHall_WebFinal','016','',0,0,'','',false,false),
('Coco Loco','coco-loco','SKUcocoloco017','06_FoodHall_WebFinal','017','',0,0,'','',false,false),
('Piña Cool','pina-cool','SKUpiñacool018','06_FoodHall_WebFinal','018','',0,0,'','',false,false),
('Paleta Helado 2','paleta-helado-2','SKUpaletahelado2019','06_FoodHall_WebFinal','019','',0,0,'','',false,false),
('Corazon Mama','corazon-mama','SKUcorazonmama001','07_DiaMadre_WebFinal','001','',0,0,'','',false,false),
('Cinta Rosal','cinta-rosal','SKUcintarosal002','07_DiaMadre_WebFinal','002','',0,0,'','',false,false),
('Maquina Coser','maquina-coser','SKUmaquinacoser003','07_DiaMadre_WebFinal','003','',0,0,'','',false,false),
('Corazon Ovillo','corazon-ovillo','SKUcorazonovillo004','07_DiaMadre_WebFinal','004','',0,0,'','',false,false),
('Mom Style','mom-style','SKUmomstyle005','07_DiaMadre_WebFinal','005','',0,0,'','',false,false),
('Mama Osa','mama-osa','SKUmamaosa006','07_DiaMadre_WebFinal','006','',0,0,'','',false,false),
('Mama #1','mama-1','SKUmama#1007','07_DiaMadre_WebFinal','007','',0,0,'','',false,false),
('MoM','mom','SKUmom008','07_DiaMadre_WebFinal','008','',0,0,'','',false,false),
('Madre e Hija','madre-e-hija','SKUmadreehija010','07_DiaMadre_WebFinal','010','',0,0,'','',false,false),
('Madre e Hija 2','madre-e-hija-2','SKUmadreehija2011','07_DiaMadre_WebFinal','011','',0,0,'','',false,false),
('Flores','flores','SKUflores012','07_DiaMadre_WebFinal','012','',0,0,'','',false,false),
('MoM 2','mom-2','SKUmom2013','07_DiaMadre_WebFinal','013','',0,0,'','',false,false),
('Tazon Corazon','tazon-corazon','SKUtazoncorazon015','07_DiaMadre_WebFinal','015','',0,0,'','',false,false),
('Sombrero Star','sombrero-star','SKUsombrerostar016','07_DiaMadre_WebFinal','016','',0,0,'','',false,false),
('Cerezas Rosal','cerezas-rosal','SKUcerezasrosal017','07_DiaMadre_WebFinal','017','',0,0,'','',false,false),
('Flor','flor','SKUflor018','07_DiaMadre_WebFinal','018','',0,0,'','',false,false),
('Beso','beso','SKUbeso019','07_DiaMadre_WebFinal','019','',0,0,'','',false,false),
('Cozaron Kpop','cozaron-kpop','SKUcozaronkpop020','07_DiaMadre_WebFinal','020','',0,0,'','',false,false),
('Labial','labial','SKUlabial021','07_DiaMadre_WebFinal','021','',0,0,'','',false,false),
('Silueta Mujer','silueta-mujer','SKUsiluetamujer022','07_DiaMadre_WebFinal','022','',0,0,'','',false,false),
('Super','super','SKUsuper023','07_DiaMadre_WebFinal','023','',0,0,'','',false,false),
('WonderWoman','wonderwoman','SKUwonderwoman024','07_DiaMadre_WebFinal','024','',0,0,'','',false,false),
('Corazon Diablo','corazon-diablo','SKUcorazondiablo025','07_DiaMadre_WebFinal','025','',0,0,'','',false,false),
('Mama Osa 2','mama-osa-2','SKUmamaosa2026','07_DiaMadre_WebFinal','026','',0,0,'','',false,false),
('Luna Sailor Moon','luna-sailor-moon','SKUlunasailormoon027','07_DiaMadre_WebFinal','027','',0,0,'','',false,false),
('Mama y Bebé','mama-y-bebe','SKUmamaybebé028','07_DiaMadre_WebFinal','028','',0,0,'','',false,false),
('Papá bigote','papa-bigote','SKUpapábigote001','08_DiaPadre_FinalWeb','001','',0,0,'','',false,false),
('Chaqueta','chaqueta','SKUchaqueta002','08_DiaPadre_FinalWeb','002','',0,0,'','',false,false),
('Best Dad','best-dad','SKUbestdad003','08_DiaPadre_FinalWeb','003','',0,0,'','',false,false),
('Llave Auto','llave-auto','SKUllaveauto004','08_DiaPadre_FinalWeb','004','',0,0,'','',false,false),
('Estoy Quebrado','estoy-quebrado','SKUestoyquebrado005','08_DiaPadre_FinalWeb','005','',0,0,'','',false,false),
('I Love You Dad','i-love-you-dad','SKUiloveyoudad006','08_DiaPadre_FinalWeb','006','',0,0,'','',false,false),
('Copa para Papá','copa-para-papa','SKUcopaparapapá007','08_DiaPadre_FinalWeb','007','',0,0,'','',false,false),
('Doh','doh','SKUdoh008','08_DiaPadre_FinalWeb','008','',0,0,'','',false,false),
('Osito Papá','osito-papa','SKUositopapá009','08_DiaPadre_FinalWeb','009','',0,0,'','',false,false),
('Papá Feliz','papa-feliz','SKUpapáfeliz010','08_DiaPadre_FinalWeb','010','',0,0,'','',false,false),
('Pesquera','pesquera','SKUpesquera011','08_DiaPadre_FinalWeb','011','',0,0,'','',false,false),
('Caña con Pez','cana-con-pez','SKUcañaconpez012','08_DiaPadre_FinalWeb','012','',0,0,'','',false,false),
('Brazo Fitness','brazo-fitness','SKUbrazofitness013','08_DiaPadre_FinalWeb','013','',0,0,'','',false,false),
('Mancuerna','mancuerna','SKUmancuerna014','08_DiaPadre_FinalWeb','014','',0,0,'','',false,false),
('Pesa Rusa','pesa-rusa','SKUpesarusa015','08_DiaPadre_FinalWeb','015','',0,0,'','',false,false),
('Gorra Nice','gorra-nice','SKUgorranice016','08_DiaPadre_FinalWeb','016','',0,0,'','',false,false),
('Señor Bigote','senor-bigote','SKUseñorbigote017','08_DiaPadre_FinalWeb','017','',0,0,'','',false,false),
('Bigote','bigote','SKUbigote018','08_DiaPadre_FinalWeb','018','',0,0,'','',false,false),
('Batman','batman','SKUbatman019','08_DiaPadre_FinalWeb','019','',0,0,'','',false,false),
('Super Dad','super-dad','SKUsuperdad023','08_DiaPadre_FinalWeb','023','',0,0,'','',false,false),
('Papá Rey','papa-rey','SKUpapárey024','08_DiaPadre_FinalWeb','024','',0,0,'','',false,false),
('Dark Vader','dark-vader','SKUdarkvader025','08_DiaPadre_FinalWeb','025','',0,0,'','',false,false),
('Yo Soy Tu Padre','yo-soy-tu-padre','SKUyosoytupadre026','08_DiaPadre_FinalWeb','026','',0,0,'','',false,false),
('Feliz Dia Papá','feliz-dia-papa','SKUfelizdiapapá027','08_DiaPadre_FinalWeb','027','',0,0,'','',false,false),
('Numero Uno','numero-uno','SKUnumerouno028','08_DiaPadre_FinalWeb','028','',0,0,'','',false,false),
('Papá de Baño','papa-de-bano','SKUpapádebaño029','08_DiaPadre_FinalWeb','029','',0,0,'','',false,false),
('Papá','papa','SKUpapá030','08_DiaPadre_FinalWeb','030','',0,0,'','',false,false),
('Gamer Dad','gamer-dad','SKUgamerdad031','08_DiaPadre_FinalWeb','031','',0,0,'','',false,false),
('Papá Play','papa-play','SKUpapáplay032','08_DiaPadre_FinalWeb','032','',0,0,'','',false,false),
('Papá Musculoso','papa-musculoso','SKUpapámusculoso033','08_DiaPadre_FinalWeb','033','',0,0,'','',false,false),
('NoPainNoGain','nopainnogain','SKUnopainnogain034','08_DiaPadre_FinalWeb','034','',0,0,'','',false,false),
('Guante Box','guante-box','SKUguantebox035','08_DiaPadre_FinalWeb','035','',0,0,'','',false,false),
('Cinturon Box','cinturon-box','SKUcinturonbox036','08_DiaPadre_FinalWeb','036','',0,0,'','',false,false),
('Casco Box','casco-box','SKUcascobox037','08_DiaPadre_FinalWeb','037','',0,0,'','',false,false),
('Saco Box','saco-box','SKUsacobox038','08_DiaPadre_FinalWeb','038','',0,0,'','',false,false),
('Guante Box 2','guante-box-2','SKUguantebox2039','08_DiaPadre_FinalWeb','039','',0,0,'','',false,false),
('Capibara','capibara','SKUcapibara001','09_Capibara_FinalWeb','001','',0,0,'','',false,false),
('Capibara 2','capibara-2','SKUcapibara2002','09_Capibara_FinalWeb','002','',0,0,'','',false,false),
('Papibara Mama','papibara-mama','SKUpapibaramama003','09_Capibara_FinalWeb','003','',0,0,'','',false,false),
('Capibara Fresa','capibara-fresa','SKUcapibarafresa004','09_Capibara_FinalWeb','004','',0,0,'','',false,false),
('Capibara Flor','capibara-flor','SKUcapibaraflor006','09_Capibara_FinalWeb','006','',0,0,'','',false,false),
('Capibara Fiestero','capibara-fiestero','SKUcapibarafiestero007','09_Capibara_FinalWeb','007','',0,0,'','',false,false),
('Neimar','neimar','SKUneimar002','11_Futbol_WebFinal','002','',0,0,'','',false,false),
('Haaland','haaland','SKUhaaland003','11_Futbol_WebFinal','003','',0,0,'','',false,false),
('Henry','henry','SKUhenry004','11_Futbol_WebFinal','004','',0,0,'','',false,false),
('Riquelme','riquelme','SKUriquelme005','11_Futbol_WebFinal','005','',0,0,'','',false,false),
('Ronaldo Nazario','ronaldo-nazario','SKUronaldonazario006','11_Futbol_WebFinal','006','',0,0,'','',false,false),
('Puyol','puyol','SKUpuyol007','11_Futbol_WebFinal','007','',0,0,'','',false,false),
('J. Alvarez','j-alvarez','SKUj.alvarez008','11_Futbol_WebFinal','008','',0,0,'','',false,false),
('Regate Pro','regate-pro','SKUregatepro009','11_Futbol_WebFinal','009','',0,0,'','',false,false),
('Tiro Gol','tiro-gol','SKUtirogol010','11_Futbol_WebFinal','010','',0,0,'','',false,false),
('Vuelo Portero','vuelo-portero','SKUvueloportero011','11_Futbol_WebFinal','011','',0,0,'','',false,false),
('Cristiano Ronaldo','cristiano-ronaldo','SKUcristianoronaldo020','11_Futbol_WebFinal','020','',0,0,'','',false,false),
('Messi','messi','SKUmessi021','11_Futbol_WebFinal','021','',0,0,'','',false,false),
('Copa Mundial','copa-mundial','SKUcopamundial022','11_Futbol_WebFinal','022','',0,0,'','',false,false),
('Balon de Futbol','balon-de-futbol','SKUbalondefutbol031','11_Futbol_WebFinal','031','',0,0,'','',false,false),
('Araña','arana','SKUaraña001','12_Halloween_SalidaWeb','001','',0,0,'','',false,false),
('Vampiresa','vampiresa','SKUvampiresa002','12_Halloween_SalidaWeb','002','',0,0,'','',false,false),
('Calabaza Halloween','calabaza-halloween','SKUcalabazahalloween003','12_Halloween_SalidaWeb','003','',0,0,'','',false,false),
('Calabaza','calabaza','SKUcalabaza004','12_Halloween_SalidaWeb','004','',0,0,'','',false,false),
('Calabera Girl','calabera-girl','SKUcalaberagirl005','12_Halloween_SalidaWeb','005','',0,0,'','',false,false),
('Calabera','calabera','SKUcalabera006','12_Halloween_SalidaWeb','006','',0,0,'','',false,false),
('Catrina','catrina','SKUcatrina007','12_Halloween_SalidaWeb','007','',0,0,'','',false,false),
('Dulce Halloween','dulce-halloween','SKUdulcehalloween008','12_Halloween_SalidaWeb','008','',0,0,'','',false,false),
('Escoba Magica','escoba-magica','SKUescobamagica009','12_Halloween_SalidaWeb','009','',0,0,'','',false,false),
('Esqueletoide','esqueletoide','SKUesqueletoide010','12_Halloween_SalidaWeb','010','',0,0,'','',false,false),
('Frankuadrado','frankuadrado','SKUfrankuadrado011','12_Halloween_SalidaWeb','011','',0,0,'','',false,false),
('Sombrero de Bruja','sombrero-de-bruja','SKUsombrerodebruja012','12_Halloween_SalidaWeb','012','',0,0,'','',false,false),
('Ojo Terror','ojo-terror','SKUojoterror013','12_Halloween_SalidaWeb','013','',0,0,'','',false,false),
('Caldero de Bruja','caldero-de-bruja','SKUcalderodebruja014','12_Halloween_SalidaWeb','014','',0,0,'','',false,false),
('Oogie Boogie','oogie-boogie','SKUoogieboogie015','12_Halloween_SalidaWeb','015','',0,0,'','',false,false),
('RIP','rip','SKUr.i.p.016','12_Halloween_SalidaWeb','016','',0,0,'','',false,false),
('Ghostface','ghostface','SKUghostface017','12_Halloween_SalidaWeb','017','',0,0,'','',false,false),
('Telaraña Halloween','telarana-halloween','SKUtelarañahalloween018','12_Halloween_SalidaWeb','018','',0,0,'','',false,false),
('Fantasmin','fantasmin','SKUfantasmin019','12_Halloween_SalidaWeb','019','',0,0,'','',false,false),
('Jack S.','jack-s','SKUjacks.020','12_Halloween_SalidaWeb','020','',0,0,'','',false,false),
('Murcielaguin','murcielaguin','SKUmurcielaguin021','12_Halloween_SalidaWeb','021','',0,0,'','',false,false),
('Murci Cute','murci-cute','SKUmurcicute022','12_Halloween_SalidaWeb','022','',0,0,'','',false,false),
('Marshall','marshall','SKUmarshall001','14_PawPatrol_FinalWeb','001','',0,0,'','',false,false),
('Chase','chase','SKUchase002','14_PawPatrol_FinalWeb','002','',0,0,'','',false,false),
('Skye','skye','SKUskye003','14_PawPatrol_FinalWeb','003','',0,0,'','',false,false),
('Rubble','rubble','SKUrubble004','14_PawPatrol_FinalWeb','004','',0,0,'','',false,false),
('Marshall 2','marshall-2','SKUmarshall2005','14_PawPatrol_FinalWeb','005','',0,0,'','',false,false),
('Huella Cachorro','huella-cachorro','SKUhuellacachorro006','14_PawPatrol_FinalWeb','006','',0,0,'','',false,false),
('Paw Patrol','paw-patrol','SKUpawpatrol007','14_PawPatrol_FinalWeb','007','',0,0,'','',false,false),
('Marshall 3','marshall-3','SKUmarshall3008','14_PawPatrol_FinalWeb','008','',0,0,'','',false,false),
('Chase 2','chase-2','SKUchase2009','14_PawPatrol_FinalWeb','009','',0,0,'','',false,false),
('Skye 2','skye-2','SKUskye2010','14_PawPatrol_FinalWeb','010','',0,0,'','',false,false),
('Rocky','rocky','SKUrocky011','14_PawPatrol_FinalWeb','011','',0,0,'','',false,false),
('Zuma','zuma','SKUzuma012','14_PawPatrol_FinalWeb','012','',0,0,'','',false,false),
('Rubble 2','rubble-2','SKUrubble2013','14_PawPatrol_FinalWeb','013','',0,0,'','',false,false),
('Everest','everest','SKUeverest014','14_PawPatrol_FinalWeb','014','',0,0,'','',false,false),
('Ryder','ryder','SKUryder015','14_PawPatrol_FinalWeb','015','',0,0,'','',false,false),
('Mystery','mystery','SKUmystery001','18_Guerreras_WebFinal','001','',0,0,'','',false,false),
('Romance','romance','SKUromance002','18_Guerreras_WebFinal','002','',0,0,'','',false,false),
('Baby','baby','SKUbaby003','18_Guerreras_WebFinal','003','',0,0,'','',false,false),
('Jinu','jinu','SKUjinu004','18_Guerreras_WebFinal','004','',0,0,'','',false,false),
('Abby','abby','SKUabby005','18_Guerreras_WebFinal','005','',0,0,'','',false,false),
('Mira','mira','SKUmira006','18_Guerreras_WebFinal','006','',0,0,'','',false,false),
('Zoey','zoey','SKUzoey007','18_Guerreras_WebFinal','007','',0,0,'','',false,false),
('Rumi','rumi','SKUrumi008','18_Guerreras_WebFinal','008','',0,0,'','',false,false),
('Derpy','derpy','SKUderpy009','18_Guerreras_WebFinal','009','',0,0,'','',false,false),
('Sussie','sussie','SKUsussie010','18_Guerreras_WebFinal','010','',0,0,'','',false,false),
('Demon','demon','SKUdemon011','18_Guerreras_WebFinal','011','',0,0,'','',false,false),
('Soda Pop','soda-pop','SKUsodapop012','18_Guerreras_WebFinal','012','',0,0,'','',false,false),
('Demon King','demon-king','SKUdemonking013','18_Guerreras_WebFinal','013','',0,0,'','',false,false),
('Cookie Pluto','cookie-pluto','SKUcookiepluto001','24_PostresDisney_FinalWeb','001','',0,0,'','',false,false),
('Cookie Donald','cookie-donald','SKUcookiedonald002','24_PostresDisney_FinalWeb','002','',0,0,'','',false,false),
('Cookie Minnie','cookie-minnie','SKUcookieminnie003','24_PostresDisney_FinalWeb','003','',0,0,'','',false,false),
('Cookie Mickey','cookie-mickey','SKUcookiemickey004','24_PostresDisney_FinalWeb','004','',0,0,'','',false,false),
('Cookie Goofy','cookie-goofy','SKUcookiegoofy005','24_PostresDisney_FinalWeb','005','',0,0,'','',false,false),
('Paleta Mickey','paleta-mickey','SKUpaletamickey006','24_PostresDisney_FinalWeb','006','',0,0,'','',false,false),
('Paleta Winnie','paleta-winnie','SKUpaletawinnie007','24_PostresDisney_FinalWeb','007','',0,0,'','',false,false),
('Muffin Mouse','muffin-mouse','SKUmuffinmouse008','24_PostresDisney_FinalWeb','008','',0,0,'','',false,false),
('IceCream Minnie','icecream-minnie','SKUicecreamminnie009','24_PostresDisney_FinalWeb','009','',0,0,'','',false,false),
('IceCream Mickey','icecream-mickey','SKUicecreammickey010','24_PostresDisney_FinalWeb','010','',0,0,'','',false,false),
('Guante MM','guante-mm','SKUguantemm011','24_PostresDisney_FinalWeb','011','',0,0,'','',false,false),
('Pantaloncillos MM','pantaloncillos-mm','SKUpantaloncillosmm012','24_PostresDisney_FinalWeb','012','',0,0,'','',false,false),
('Zapatos MM','zapatos-mm','SKUzapatosmm013','24_PostresDisney_FinalWeb','013','',0,0,'','',false,false),
('Liston MM','liston-mm','SKUlistonmm014','24_PostresDisney_FinalWeb','014','',0,0,'','',false,false),
('Reno Navideño','reno-navideno','SKUrenonavideño001','26_Navidad_FinalWeb','001','',0,0,'','',false,false),
('Corona de Navidad','corona-de-navidad','SKUcoronadenavidad002','26_Navidad_FinalWeb','002','',0,0,'','',false,false),
('Esfera de Navidad','esfera-de-navidad','SKUesferadenavidad003','26_Navidad_FinalWeb','003','',0,0,'','',false,false),
('Dulce de Navidad','dulce-de-navidad','SKUdulcedenavidad004','26_Navidad_FinalWeb','004','',0,0,'','',false,false),
('Santa Atrapado','santa-atrapado','SKUsantaatrapado005','26_Navidad_FinalWeb','005','',0,0,'','',false,false),
('Huella Navidad','huella-navidad','SKUhuellanavidad006','26_Navidad_FinalWeb','006','',0,0,'','',false,false),
('Navidad Perruna','navidad-perruna','SKUnavidadperruna007','26_Navidad_FinalWeb','007','',0,0,'','',false,false),
('Muñeco de Navidad','muneco-de-navidad','SKUmuñecodenavidad008','26_Navidad_FinalWeb','008','',0,0,'','',false,false),
('Rodolfo Reno','rodolfo-reno','SKUrodolforeno009','26_Navidad_FinalWeb','009','',0,0,'','',false,false),
('Santa Claus','santa-claus','SKUsantaclaus010','26_Navidad_FinalWeb','010','',0,0,'','',false,false),
('Regalo de Navidad','regalo-de-navidad','SKUregalodenavidad011','26_Navidad_FinalWeb','011','',0,0,'','',false,false),
('Vela Navideña','vela-navidena','SKUvelanavideña012','26_Navidad_FinalWeb','012','',0,0,'','',false,false),
('Esfera de Navidad 2','esfera-de-navidad-2','SKUesferadenavidad2013','26_Navidad_FinalWeb','013','',0,0,'','',false,false),
('Muñeco de Jengibre','muneco-de-jengibre','SKUmuñecodejengibre014','26_Navidad_FinalWeb','014','',0,0,'','',false,false),
('Muñeco de Jengibre 2','muneco-de-jengibre-2','SKUmuñecodejengibre2015','26_Navidad_FinalWeb','015','',0,0,'','',false,false),
('Arbol de Navidad','arbol-de-navidad','SKUarboldenavidad016','26_Navidad_FinalWeb','016','',0,0,'','',false,false),
('El Grinch','el-grinch','SKUelgrinch017','26_Navidad_FinalWeb','017','',0,0,'','',false,false),
('Casa de Navidad','casa-de-navidad','SKUcasadenavidad018','26_Navidad_FinalWeb','018','',0,0,'','',false,false),
('Corona de Navidad 2','corona-de-navidad-2','SKUcoronadenavidad2019','26_Navidad_FinalWeb','019','',0,0,'','',false,false),
('Kitty Navideno','kitty-navideno','SKUkittynavideno020','26_Navidad_FinalWeb','020','',0,0,'','',false,false),
('Snoopy Navideño','snoopy-navideno','SKUsnoopynavideño021','26_Navidad_FinalWeb','021','',0,0,'','',false,false),
('Stitch Hawai','stitch-hawai','SKUstitchhawai001','31_Sticht_FinalWeb','001','',0,0,'','',false,false),
('Stitch Hi','stitch-hi','SKUstitchhi002','31_Sticht_FinalWeb','002','',0,0,'','',false,false),
('Stitch Bonito','stitch-bonito','SKUstitchbonito003','31_Sticht_FinalWeb','003','',0,0,'','',false,false),
('Angel Back','angel-back','SKUangelback004','31_Sticht_FinalWeb','004','',0,0,'','',false,false),
('Stitch Head','stitch-head','SKUstitchhead005','31_Sticht_FinalWeb','005','',0,0,'','',false,false),
('Angel','angel','SKUangel006','31_Sticht_FinalWeb','006','',0,0,'','',false,false),
('Angel In Love','angel-in-love','SKUangelinlove007','31_Sticht_FinalWeb','007','',0,0,'','',false,false),
('LiLo Hawai','lilo-hawai','SKUlilohawai008','31_Sticht_FinalWeb','008','',0,0,'','',false,false),
('Agente Pleakley','agente-pleakley','SKUagentepleakley009','31_Sticht_FinalWeb','009','',0,0,'','',false,false),
('Jumba Jookiba','jumba-jookiba','SKUjumbajookiba010','31_Sticht_FinalWeb','010','',0,0,'','',false,false),
('Stitch','stitch','SKUstitch011','31_Sticht_FinalWeb','011','',0,0,'','',false,false),
('Tabla de Surf','tabla-de-surf','SKUtabladesurf012','31_Sticht_FinalWeb','012','',0,0,'','',false,false),
('Piña Hawai','pina-hawai','SKUpiñahawai013','31_Sticht_FinalWeb','013','',0,0,'','',false,false),
('Arma Espacial','arma-espacial','SKUarmaespacial014','31_Sticht_FinalWeb','014','',0,0,'','',false,false),
('LiLo','lilo','SKUlilo015','31_Sticht_FinalWeb','015','',0,0,'','',false,false),
('Babero','babero','SKUbabero001','32_BabyShower - FinalWeb','001','',0,0,'','',false,false),
('Biberon','biberon','SKUbiberon002','32_BabyShower - FinalWeb','002','',0,0,'','',false,false),
('Chupete','chupete','SKUchupete003','32_BabyShower - FinalWeb','003','',0,0,'','',false,false),
('Piecito','piecito','SKUpiecito004','32_BabyShower - FinalWeb','004','',0,0,'','',false,false),
('Test Positivo','test-positivo','SKUtestpositivo005','32_BabyShower - FinalWeb','005','',0,0,'','',false,false),
('Nene','nene','SKUnene006','32_BabyShower - FinalWeb','006','',0,0,'','',false,false),
('Nena','nena','SKUnena007','32_BabyShower - FinalWeb','007','',0,0,'','',false,false),
('Enterito Azul','enterito-azul','SKUenteritoazul008','32_BabyShower - FinalWeb','008','',0,0,'','',false,false),
('Cascabel','cascabel','SKUcascabel009','32_BabyShower - FinalWeb','009','',0,0,'','',false,false),
('Chupete 2','chupete-2','SKUchupete2010','32_BabyShower - FinalWeb','010','',0,0,'','',false,false),
('Cigüeña','ciguena','SKUcigüeña011','32_BabyShower - FinalWeb','011','',0,0,'','',false,false),
('Coche','coche','SKUcoche012','32_BabyShower - FinalWeb','012','',0,0,'','',false,false),
('Gorro Lana','gorro-lana','SKUgorrolana013','32_BabyShower - FinalWeb','013','',0,0,'','',false,false),
('Futura Mamá','futura-mama','SKUfuturamamá014','32_BabyShower - FinalWeb','014','',0,0,'','',false,false),
('Osito Rosa','osito-rosa','SKUositorosa015','32_BabyShower - FinalWeb','015','',0,0,'','',false,false),
('Pato de Hule','pato-de-hule','SKUpatodehule016','32_BabyShower - FinalWeb','016','',0,0,'','',false,false),
('Pañal','panal','SKUpañal017','32_BabyShower - FinalWeb','017','',0,0,'','',false,false),
('Biberon 2','biberon-2','SKUbiberon2018','32_BabyShower - FinalWeb','018','',0,0,'','',false,false),
('Hada Gatina','hada-gatina','SKUhadagatina001','34_CadaDeGabby_WebFinal','001','',0,0,'','',false,false),
('Pastelillo','pastelillo','SKUpastelillo002','34_CadaDeGabby_WebFinal','002','',0,0,'','',false,false),
('Pandy Patas','pandy-patas','SKUpandypatas003','34_CadaDeGabby_WebFinal','003','',0,0,'','',false,false),
('Gabby','gabby','SKUgabby004','34_CadaDeGabby_WebFinal','004','',0,0,'','',false,false),
('Siregata','siregata','SKUsiregata005','34_CadaDeGabby_WebFinal','005','',0,0,'','',false,false),
('DJ Capucha','dj-capucha','SKUdjcapucha006','34_CadaDeGabby_WebFinal','006','',0,0,'','',false,false),
('Bebé Caja','bebe-caja','SKUbebécaja007','34_CadaDeGabby_WebFinal','007','',0,0,'','',false,false),
('Escurrigato','escurrigato','SKUescurrigato008','34_CadaDeGabby_WebFinal','008','',0,0,'','',false,false),
('Winnie','winnie','SKUwinnie001','35_WinniePooh_FinalWeb','001','',0,0,'','',false,false),
('Tigger','tigger','SKUtigger002','35_WinniePooh_FinalWeb','002','',0,0,'','',false,false),
('Piglet','piglet','SKUpiglet003','35_WinniePooh_FinalWeb','003','',0,0,'','',false,false),
('Hunny','hunny','SKUhunny004','35_WinniePooh_FinalWeb','004','',0,0,'','',false,false),
('Winnie Feliz','winnie-feliz','SKUwinniefeliz005','35_WinniePooh_FinalWeb','005','',0,0,'','',false,false),
('Winnie Globos','winnie-globos','SKUwinnieglobos006','35_WinniePooh_FinalWeb','006','',0,0,'','',false,false),
('Piglet 2','piglet-2','SKUpiglet2007','35_WinniePooh_FinalWeb','007','',0,0,'','',false,false),
('Tigger 2','tigger-2','SKUtigger2009','35_WinniePooh_FinalWeb','009','',0,0,'','',false,false),
('Winnie Curioso','winnie-curioso','SKUwinniecurioso010','35_WinniePooh_FinalWeb','010','',0,0,'','',false,false),
('Hamm','hamm','SKUhamm001','40_ToyStory_WebFinal','001','',0,0,'','',false,false),
('Buzz','buzz','SKUbuzz002','40_ToyStory_WebFinal','002','',0,0,'','',false,false),
('Woody','woody','SKUwoody003','40_ToyStory_WebFinal','003','',0,0,'','',false,false),
('Slinky','slinky','SKUslinky004','40_ToyStory_WebFinal','004','',0,0,'','',false,false),
('Duke','duke','SKUduke005','40_ToyStory_WebFinal','005','',0,0,'','',false,false),
('Jessie','jessie','SKUjessie006','40_ToyStory_WebFinal','006','',0,0,'','',false,false),
('Rex','rex','SKUrex007','40_ToyStory_WebFinal','007','',0,0,'','',false,false),
('Forky','forky','SKUforky008','40_ToyStory_WebFinal','008','',0,0,'','',false,false),
('Zurg','zurg','SKUzurg009','40_ToyStory_WebFinal','009','',0,0,'','',false,false),
('Betty','betty','SKUbetty010','40_ToyStory_WebFinal','010','',0,0,'','',false,false),
('Marcianito','marcianito','SKUmarcianito011','40_ToyStory_WebFinal','011','',0,0,'','',false,false),
('Sr Cara de Papa','sr-cara-de-papa','SKUsrcaradepapa012','40_ToyStory_WebFinal','012','',0,0,'','',false,false),
('Lilypad','lilypad','SKUlilypad013','40_ToyStory_WebFinal','013','',0,0,'','',false,false),
('Pelota TS','pelota-ts','SKUpelotats014','40_ToyStory_WebFinal','014','',0,0,'','',false,false),
('Buzz de Andy','buzz-de-andy','SKUbuzzdeandy015','40_ToyStory_WebFinal','015','',0,0,'','',false,false),
('Woody de Andy','woody-de-andy','SKUwoodydeandy016','40_ToyStory_WebFinal','016','',0,0,'','',false,false),
('Snoopy','snoopy','SKUsnoopy001','41_Snoopy_SalidaWeb','001','',0,0,'','',false,false),
('Woodstock','woodstock','SKUwoodstock002','41_Snoopy_SalidaWeb','002','',0,0,'','',false,false),
('Charlie Brown','charlie-brown','SKUcharliebrown003','41_Snoopy_SalidaWeb','003','',0,0,'','',false,false),
('Snoopy Chill','snoopy-chill','SKUsnoopychill004','41_Snoopy_SalidaWeb','004','',0,0,'','',false,false),
('Sally Brown','sally-brown','SKUsallybrown005','41_Snoopy_SalidaWeb','005','',0,0,'','',false,false),
('Lucy van Pelt','lucy-van-pelt','SKUlucyvanpelt006','41_Snoopy_SalidaWeb','006','',0,0,'','',false,false),
('Arenita','arenita','SKUarenita001','42_BobEsponja_FinalWeb','001','',0,0,'','',false,false),
('Bob Esponja','bob-esponja','SKUbobesponja002','42_BobEsponja_FinalWeb','002','',0,0,'','',false,false),
('Calamardo','calamardo','SKUcalamardo003','42_BobEsponja_FinalWeb','003','',0,0,'','',false,false),
('Gary','gary','SKUgary004','42_BobEsponja_FinalWeb','004','',0,0,'','',false,false),
('Medusa','medusa','SKUmedusa005','42_BobEsponja_FinalWeb','005','',0,0,'','',false,false),
('Patricio','patricio','SKUpatricio006','42_BobEsponja_FinalWeb','006','',0,0,'','',false,false),
('Piña Bajo del Mar','pina-bajo-del-mar','SKUpiñabajodelmar007','42_BobEsponja_FinalWeb','007','',0,0,'','',false,false),
('Planton','planton','SKUplanton008','42_BobEsponja_FinalWeb','008','',0,0,'','',false,false),
('Abejita Baby','abejita-baby','SKUabejitababy001','44_BabyAnimales_FinalWeb','001','',0,0,'','',false,false),
('Burrito Baby','burrito-baby','SKUburritobaby002','44_BabyAnimales_FinalWeb','002','',0,0,'','',false,false),
('Cebrita Baby','cebrita-baby','SKUcebritababy003','44_BabyAnimales_FinalWeb','003','',0,0,'','',false,false),
('Cerdito Baby','cerdito-baby','SKUcerditobaby004','44_BabyAnimales_FinalWeb','004','',0,0,'','',false,false),
('Conejuto Baby','conejuto-baby','SKUconejutobaby005','44_BabyAnimales_FinalWeb','005','',0,0,'','',false,false),
('Dino Baby','dino-baby','SKUdinobaby006','44_BabyAnimales_FinalWeb','006','',0,0,'','',false,false),
('Elefantito Baby','elefantito-baby','SKUelefantitobaby007','44_BabyAnimales_FinalWeb','007','',0,0,'','',false,false),
('Puequito Espin Baby','puequito-espin-baby','SKUpuequitoespinbaby008','44_BabyAnimales_FinalWeb','008','',0,0,'','',false,false),
('Gatito Baby','gatito-baby','SKUgatitobaby009','44_BabyAnimales_FinalWeb','009','',0,0,'','',false,false),
('Jirafita Baby','jirafita-baby','SKUjirafitababy010','44_BabyAnimales_FinalWeb','010','',0,0,'','',false,false),
('Tigriro Baby','tigriro-baby','SKUtigrirobaby011','44_BabyAnimales_FinalWeb','011','',0,0,'','',false,false),
('Leoncito Baby','leoncito-baby','SKUleoncitobaby012','44_BabyAnimales_FinalWeb','012','',0,0,'','',false,false),
('Llamita Baby','llamita-baby','SKUllamitababy013','44_BabyAnimales_FinalWeb','013','',0,0,'','',false,false),
('Monito Baby','monito-baby','SKUmonitobaby014','44_BabyAnimales_FinalWeb','014','',0,0,'','',false,false),
('Pandita Baby','pandita-baby','SKUpanditababy015','44_BabyAnimales_FinalWeb','015','',0,0,'','',false,false),
('Patito Baby','patito-baby','SKUpatitobaby016','44_BabyAnimales_FinalWeb','016','',0,0,'','',false,false),
('Pingüinito Baby','pinguinito-baby','SKUpingüinitobaby017','44_BabyAnimales_FinalWeb','017','',0,0,'','',false,false),
('Serpientin Baby','serpientin-baby','SKUserpientinbaby018','44_BabyAnimales_FinalWeb','018','',0,0,'','',false,false),
('Vaquita Baby','vaquita-baby','SKUvaquitababy019','44_BabyAnimales_FinalWeb','019','',0,0,'','',false,false),
('Zorrito Baby','zorrito-baby','SKUzorritobaby020','44_BabyAnimales_FinalWeb','020','',0,0,'','',false,false),
('Copihue','copihue','SKUcopihue001','45_FiestasPatrias_FinalWeb','001','',0,0,'','',false,false),
('Volantin','volantin','SKUvolantin002','45_FiestasPatrias_FinalWeb','002','',0,0,'','',false,false),
('Banderita Chilena','banderita-chilena','SKUbanderitachilena003','45_FiestasPatrias_FinalWeb','003','',0,0,'','',false,false),
('Empanada Chilena','empanada-chilena','SKUempanadachilena004','45_FiestasPatrias_FinalWeb','004','',0,0,'','',false,false),
('Empanada Feliz','empanada-feliz','SKUempanadafeliz005','45_FiestasPatrias_FinalWeb','005','',0,0,'','',false,false),
('Terremoto Chileno','terremoto-chileno','SKUterremotochileno006','45_FiestasPatrias_FinalWeb','006','',0,0,'','',false,false),
('Escudo Chileno','escudo-chileno','SKUescudochileno007','45_FiestasPatrias_FinalWeb','007','',0,0,'','',false,false),
('Circo Chileno','circo-chileno','SKUcircochileno008','45_FiestasPatrias_FinalWeb','008','',0,0,'','',false,false),
('Corazon Chileno','corazon-chileno','SKUcorazonchileno009','45_FiestasPatrias_FinalWeb','009','',0,0,'','',false,false),
('Choripan','choripan','SKUchoripan010','45_FiestasPatrias_FinalWeb','010','',0,0,'','',false,false),
('YoYo','yoyo','SKUyoyo011','45_FiestasPatrias_FinalWeb','011','',0,0,'','',false,false),
('Trompo Chileno','trompo-chileno','SKUtrompochileno012','45_FiestasPatrias_FinalWeb','012','',0,0,'','',false,false)
on conflict (sku) do update set name=excluded.name, slug=excluded.slug, source_group=excluded.source_group, source_number=excluded.source_number;

with links(sku,category_slug) as (values
('SKUbluey001','todo-bluey'),
('SKUbluey001','todo-cartoon'),
('SKUbluey001','todo-ninos'),
('SKUbingo002','todo-bluey'),
('SKUbingo002','todo-cartoon'),
('SKUbingo002','todo-ninos'),
('SKUunicorse003','todo-bluey'),
('SKUunicorse003','todo-cartoon'),
('SKUunicorse003','todo-ninos'),
('SKUb&b004','todo-bluey'),
('SKUb&b004','todo-cartoon'),
('SKUb&b004','todo-ninos'),
('SKUmom&dad005','todo-bluey'),
('SKUmom&dad005','todo-cartoon'),
('SKUmom&dad005','todo-ninos'),
('SKUbluey2006','todo-bluey'),
('SKUbluey2006','todo-cartoon'),
('SKUbluey2006','todo-ninos'),
('SKUpompom007','todo-bluey'),
('SKUpompom007','todo-cartoon'),
('SKUpompom007','todo-ninos'),
('SKUcoco008','todo-bluey'),
('SKUcoco008','todo-cartoon'),
('SKUcoco008','todo-ninos'),
('SKUb&bcartoon009','todo-bluey'),
('SKUb&bcartoon009','todo-cartoon'),
('SKUb&bcartoon009','todo-ninos'),
('SKUb&brainbow010','todo-bluey'),
('SKUb&brainbow010','todo-cartoon'),
('SKUb&brainbow010','todo-ninos'),
('SKUpulpito001','todo-marinos-cute'),
('SKUpulpito001','todo-cartoon'),
('SKUpulpito001','todo-ninos'),
('SKUdelfin002','todo-marinos-cute'),
('SKUdelfin002','todo-cartoon'),
('SKUdelfin002','todo-ninos'),
('SKUballenita003','todo-marinos-cute'),
('SKUballenita003','todo-cartoon'),
('SKUballenita003','todo-ninos'),
('SKUdelfin2004','todo-marinos-cute'),
('SKUdelfin2004','todo-cartoon'),
('SKUdelfin2004','todo-ninos'),
('SKUtortuguita005','todo-marinos-cute'),
('SKUtortuguita005','todo-cartoon'),
('SKUtortuguita005','todo-ninos'),
('SKUtiburoncin006','todo-marinos-cute'),
('SKUtiburoncin006','todo-cartoon'),
('SKUtiburoncin006','todo-ninos'),
('SKUestrellita007','todo-marinos-cute'),
('SKUestrellita007','todo-cartoon'),
('SKUestrellita007','todo-ninos'),
('SKUlucario001','todo-pokemon'),
('SKUlucario001','todo-cartoon'),
('SKUlucario001','todo-ninos'),
('SKUlucario001','todo-anime'),
('SKUsquirtle002','todo-pokemon'),
('SKUsquirtle002','todo-cartoon'),
('SKUsquirtle002','todo-ninos'),
('SKUsquirtle002','todo-anime'),
('SKUjigglypuff003','todo-pokemon'),
('SKUjigglypuff003','todo-cartoon'),
('SKUjigglypuff003','todo-ninos'),
('SKUjigglypuff003','todo-anime'),
('SKUmewtwo004','todo-pokemon'),
('SKUmewtwo004','todo-cartoon'),
('SKUmewtwo004','todo-ninos'),
('SKUmewtwo004','todo-anime'),
('SKUcharmander005','todo-pokemon'),
('SKUcharmander005','todo-cartoon'),
('SKUcharmander005','todo-ninos'),
('SKUcharmander005','todo-anime'),
('SKUeevee006','todo-pokemon'),
('SKUeevee006','todo-cartoon'),
('SKUeevee006','todo-ninos'),
('SKUeevee006','todo-anime'),
('SKUpikachu2007','todo-pokemon'),
('SKUpikachu2007','todo-cartoon'),
('SKUpikachu2007','todo-ninos'),
('SKUpikachu2007','todo-anime'),
('SKUbulbasaur008','todo-pokemon'),
('SKUbulbasaur008','todo-cartoon'),
('SKUbulbasaur008','todo-ninos'),
('SKUbulbasaur008','todo-anime'),
('SKUdragonite009','todo-pokemon'),
('SKUdragonite009','todo-cartoon'),
('SKUdragonite009','todo-ninos'),
('SKUdragonite009','todo-anime'),
('SKUgengar010','todo-pokemon'),
('SKUgengar010','todo-cartoon'),
('SKUgengar010','todo-ninos'),
('SKUgengar010','todo-anime'),
('SKUpokeball011','todo-pokemon'),
('SKUpokeball011','todo-cartoon'),
('SKUpokeball011','todo-ninos'),
('SKUpokeball011','todo-anime'),
('SKUfacesquirtle012','todo-pokemon'),
('SKUfacesquirtle012','todo-cartoon'),
('SKUfacesquirtle012','todo-ninos'),
('SKUfacesquirtle012','todo-anime'),
('SKUfacecharmander013','todo-pokemon'),
('SKUfacecharmander013','todo-cartoon'),
('SKUfacecharmander013','todo-ninos'),
('SKUfacecharmander013','todo-anime'),
('SKUfacepikachu014','todo-pokemon'),
('SKUfacepikachu014','todo-cartoon'),
('SKUfacepikachu014','todo-ninos'),
('SKUfacepikachu014','todo-anime'),
('SKUfacebulbasaur015','todo-pokemon'),
('SKUfacebulbasaur015','todo-cartoon'),
('SKUfacebulbasaur015','todo-ninos'),
('SKUfacebulbasaur015','todo-anime'),
('SKUpikachu016','todo-pokemon'),
('SKUpikachu016','todo-cartoon'),
('SKUpikachu016','todo-ninos'),
('SKUpikachu016','todo-anime'),
('SKUspiderface001','todo-spiderman'),
('SKUspiderface001','todo-marvel'),
('SKUspiderface001','todo-cartoon'),
('SKUspiderface001','todo-ninos'),
('SKUspidermask002','todo-spiderman'),
('SKUspidermask002','todo-marvel'),
('SKUspidermask002','todo-cartoon'),
('SKUspidermask002','todo-ninos'),
('SKUspiderlogo003','todo-spiderman'),
('SKUspiderlogo003','todo-marvel'),
('SKUspiderlogo003','todo-cartoon'),
('SKUspiderlogo003','todo-ninos'),
('SKUspidermancute004','todo-spiderman'),
('SKUspidermancute004','todo-marvel'),
('SKUspidermancute004','todo-cartoon'),
('SKUspidermancute004','todo-ninos'),
('SKUspidermanlisto005','todo-spiderman'),
('SKUspidermanlisto005','todo-marvel'),
('SKUspidermanlisto005','todo-cartoon'),
('SKUspidermanlisto005','todo-ninos'),
('SKUspidermanshibi006','todo-spiderman'),
('SKUspidermanshibi006','todo-marvel'),
('SKUspidermanshibi006','todo-cartoon'),
('SKUspidermanshibi006','todo-ninos'),
('SKUspidy007','todo-spiderman'),
('SKUspidy007','todo-marvel'),
('SKUspidy007','todo-cartoon'),
('SKUspidy007','todo-ninos'),
('SKUsentidoaracnido008','todo-spiderman'),
('SKUsentidoaracnido008','todo-marvel'),
('SKUsentidoaracnido008','todo-cartoon'),
('SKUsentidoaracnido008','todo-ninos'),
('SKUescudocapamerica001','todo-marvel'),
('SKUescudocapamerica001','todo-superheroes'),
('SKUescudocapamerica001','todo-ninos'),
('SKUescudocapamerica001','todo-cartoon'),
('SKUlogoavengers003','todo-marvel'),
('SKUlogoavengers003','todo-superheroes'),
('SKUlogoavengers003','todo-ninos'),
('SKUlogoavengers003','todo-cartoon'),
('SKUmartillothor004','todo-marvel'),
('SKUmartillothor004','todo-superheroes'),
('SKUmartillothor004','todo-ninos'),
('SKUmartillothor004','todo-cartoon'),
('SKUguantelete005','todo-marvel'),
('SKUguantelete005','todo-superheroes'),
('SKUguantelete005','todo-ninos'),
('SKUguantelete005','todo-cartoon'),
('SKUpuñohulk007','todo-marvel'),
('SKUpuñohulk007','todo-superheroes'),
('SKUpuñohulk007','todo-ninos'),
('SKUpuñohulk007','todo-cartoon'),
('SKUcascoironman008','todo-marvel'),
('SKUcascoironman008','todo-superheroes'),
('SKUcascoironman008','todo-ninos'),
('SKUcascoironman008','todo-cartoon'),
('SKUmascarawolverine009','todo-marvel'),
('SKUmascarawolverine009','todo-superheroes'),
('SKUmascarawolverine009','todo-ninos'),
('SKUmascarawolverine009','todo-cartoon'),
('SKUlogodeadpool010','todo-marvel'),
('SKUlogodeadpool010','todo-superheroes'),
('SKUlogodeadpool010','todo-ninos'),
('SKUlogodeadpool010','todo-cartoon'),
('SKUcupcake001','todo-foodhall'),
('SKUcupcake001','todo-cartoon'),
('SKUqueso002','todo-foodhall'),
('SKUqueso002','todo-cartoon'),
('SKUmalteada003','todo-foodhall'),
('SKUmalteada003','todo-cartoon'),
('SKUsandia004','todo-foodhall'),
('SKUsandia004','todo-cartoon'),
('SKUbanana005','todo-foodhall'),
('SKUbanana005','todo-cartoon'),
('SKUhamburguesa007','todo-foodhall'),
('SKUhamburguesa007','todo-cartoon'),
('SKUconohelado008','todo-foodhall'),
('SKUconohelado008','todo-cartoon'),
('SKUpaletahelado009','todo-foodhall'),
('SKUpaletahelado009','todo-cartoon'),
('SKUpanrebanada010','todo-foodhall'),
('SKUpanrebanada010','todo-cartoon'),
('SKUcaramelo011','todo-foodhall'),
('SKUcaramelo011','todo-cartoon'),
('SKUpiruleta013','todo-foodhall'),
('SKUpiruleta013','todo-cartoon'),
('SKUshop014','todo-foodhall'),
('SKUshop014','todo-cartoon'),
('SKUtorta015','todo-foodhall'),
('SKUtorta015','todo-cartoon'),
('SKUvasodejugo016','todo-foodhall'),
('SKUvasodejugo016','todo-cartoon'),
('SKUcocoloco017','todo-foodhall'),
('SKUcocoloco017','todo-cartoon'),
('SKUpiñacool018','todo-foodhall'),
('SKUpiñacool018','todo-cartoon'),
('SKUpaletahelado2019','todo-foodhall'),
('SKUpaletahelado2019','todo-cartoon'),
('SKUcorazonmama001','todo-mama'),
('SKUcorazonmama001','todo-mujer'),
('SKUcintarosal002','todo-mama'),
('SKUcintarosal002','todo-mujer'),
('SKUmaquinacoser003','todo-mama'),
('SKUmaquinacoser003','todo-mujer'),
('SKUcorazonovillo004','todo-mama'),
('SKUcorazonovillo004','todo-mujer'),
('SKUmomstyle005','todo-mama'),
('SKUmomstyle005','todo-mujer'),
('SKUmamaosa006','todo-mama'),
('SKUmamaosa006','todo-mujer'),
('SKUmama#1007','todo-mama'),
('SKUmama#1007','todo-mujer'),
('SKUmom008','todo-mama'),
('SKUmom008','todo-mujer'),
('SKUmadreehija010','todo-mama'),
('SKUmadreehija010','todo-mujer'),
('SKUmadreehija2011','todo-mama'),
('SKUmadreehija2011','todo-mujer'),
('SKUflores012','todo-mama'),
('SKUflores012','todo-mujer'),
('SKUmom2013','todo-mama'),
('SKUmom2013','todo-mujer'),
('SKUtazoncorazon015','todo-mama'),
('SKUtazoncorazon015','todo-mujer'),
('SKUsombrerostar016','todo-mama'),
('SKUsombrerostar016','todo-mujer'),
('SKUcerezasrosal017','todo-mama'),
('SKUcerezasrosal017','todo-mujer'),
('SKUflor018','todo-mama'),
('SKUflor018','todo-mujer'),
('SKUbeso019','todo-mama'),
('SKUbeso019','todo-mujer'),
('SKUcozaronkpop020','todo-mama'),
('SKUcozaronkpop020','todo-mujer'),
('SKUlabial021','todo-mama'),
('SKUlabial021','todo-mujer'),
('SKUsiluetamujer022','todo-mama'),
('SKUsiluetamujer022','todo-mujer'),
('SKUsuper023','todo-mama'),
('SKUsuper023','todo-mujer'),
('SKUwonderwoman024','todo-mama'),
('SKUwonderwoman024','todo-mujer'),
('SKUcorazondiablo025','todo-mama'),
('SKUcorazondiablo025','todo-mujer'),
('SKUmamaosa2026','todo-mama'),
('SKUmamaosa2026','todo-mujer'),
('SKUlunasailormoon027','todo-mama'),
('SKUlunasailormoon027','todo-mujer'),
('SKUmamaybebé028','todo-mama'),
('SKUmamaybebé028','todo-mujer'),
('SKUpapábigote001','todo-papa'),
('SKUpapábigote001','todo-hombre'),
('SKUchaqueta002','todo-papa'),
('SKUchaqueta002','todo-hombre'),
('SKUbestdad003','todo-papa'),
('SKUbestdad003','todo-hombre'),
('SKUllaveauto004','todo-papa'),
('SKUllaveauto004','todo-hombre'),
('SKUestoyquebrado005','todo-papa'),
('SKUestoyquebrado005','todo-hombre'),
('SKUiloveyoudad006','todo-papa'),
('SKUiloveyoudad006','todo-hombre'),
('SKUcopaparapapá007','todo-papa'),
('SKUcopaparapapá007','todo-hombre'),
('SKUdoh008','todo-papa'),
('SKUdoh008','todo-hombre'),
('SKUositopapá009','todo-papa'),
('SKUositopapá009','todo-hombre'),
('SKUpapáfeliz010','todo-papa'),
('SKUpapáfeliz010','todo-hombre'),
('SKUpesquera011','todo-papa'),
('SKUpesquera011','todo-hombre'),
('SKUcañaconpez012','todo-papa'),
('SKUcañaconpez012','todo-hombre'),
('SKUbrazofitness013','todo-papa'),
('SKUbrazofitness013','todo-hombre'),
('SKUmancuerna014','todo-papa'),
('SKUmancuerna014','todo-hombre'),
('SKUmancuerna014','todo-deporte'),
('SKUpesarusa015','todo-papa'),
('SKUpesarusa015','todo-hombre'),
('SKUpesarusa015','todo-deporte'),
('SKUgorranice016','todo-papa'),
('SKUgorranice016','todo-hombre'),
('SKUseñorbigote017','todo-papa'),
('SKUseñorbigote017','todo-hombre'),
('SKUbigote018','todo-papa'),
('SKUbigote018','todo-hombre'),
('SKUbatman019','todo-papa'),
('SKUbatman019','todo-hombre'),
('SKUsuperdad023','todo-papa'),
('SKUsuperdad023','todo-hombre'),
('SKUpapárey024','todo-papa'),
('SKUpapárey024','todo-hombre'),
('SKUdarkvader025','todo-papa'),
('SKUdarkvader025','todo-hombre'),
('SKUyosoytupadre026','todo-papa'),
('SKUyosoytupadre026','todo-hombre'),
('SKUfelizdiapapá027','todo-papa'),
('SKUfelizdiapapá027','todo-hombre'),
('SKUnumerouno028','todo-papa'),
('SKUnumerouno028','todo-hombre'),
('SKUpapádebaño029','todo-papa'),
('SKUpapádebaño029','todo-hombre'),
('SKUpapá030','todo-papa'),
('SKUpapá030','todo-hombre'),
('SKUgamerdad031','todo-papa'),
('SKUgamerdad031','todo-hombre'),
('SKUgamerdad031','todo-gamer'),
('SKUpapáplay032','todo-papa'),
('SKUpapáplay032','todo-hombre'),
('SKUpapáplay032','todo-gamer'),
('SKUpapámusculoso033','todo-papa'),
('SKUpapámusculoso033','todo-hombre'),
('SKUpapámusculoso033','todo-deporte'),
('SKUnopainnogain034','todo-papa'),
('SKUnopainnogain034','todo-hombre'),
('SKUnopainnogain034','todo-deporte'),
('SKUguantebox035','todo-papa'),
('SKUguantebox035','todo-hombre'),
('SKUguantebox035','todo-deporte'),
('SKUcinturonbox036','todo-papa'),
('SKUcinturonbox036','todo-hombre'),
('SKUcinturonbox036','todo-deporte'),
('SKUcascobox037','todo-papa'),
('SKUcascobox037','todo-hombre'),
('SKUcascobox037','todo-deporte'),
('SKUsacobox038','todo-papa'),
('SKUsacobox038','todo-hombre'),
('SKUsacobox038','todo-deporte'),
('SKUguantebox2039','todo-papa'),
('SKUguantebox2039','todo-hombre'),
('SKUguantebox2039','todo-deporte'),
('SKUcapibara001','todo-capibara'),
('SKUcapibara001','todo-animales'),
('SKUcapibara001','todo-ninos'),
('SKUcapibara2002','todo-capibara'),
('SKUcapibara2002','todo-animales'),
('SKUcapibara2002','todo-ninos'),
('SKUpapibaramama003','todo-capibara'),
('SKUpapibaramama003','todo-animales'),
('SKUpapibaramama003','todo-ninos'),
('SKUcapibarafresa004','todo-capibara'),
('SKUcapibarafresa004','todo-animales'),
('SKUcapibarafresa004','todo-ninos'),
('SKUcapibaraflor006','todo-capibara'),
('SKUcapibaraflor006','todo-animales'),
('SKUcapibaraflor006','todo-ninos'),
('SKUcapibarafiestero007','todo-capibara'),
('SKUcapibarafiestero007','todo-animales'),
('SKUcapibarafiestero007','todo-ninos'),
('SKUneimar002','todo-futbol'),
('SKUneimar002','todo-hombre'),
('SKUneimar002','todo-mujer'),
('SKUneimar002','todo-deporte'),
('SKUhaaland003','todo-futbol'),
('SKUhaaland003','todo-hombre'),
('SKUhaaland003','todo-mujer'),
('SKUhaaland003','todo-deporte'),
('SKUhenry004','todo-futbol'),
('SKUhenry004','todo-hombre'),
('SKUhenry004','todo-mujer'),
('SKUhenry004','todo-deporte'),
('SKUriquelme005','todo-futbol'),
('SKUriquelme005','todo-hombre'),
('SKUriquelme005','todo-mujer'),
('SKUriquelme005','todo-deporte'),
('SKUronaldonazario006','todo-futbol'),
('SKUronaldonazario006','todo-hombre'),
('SKUronaldonazario006','todo-mujer'),
('SKUronaldonazario006','todo-deporte'),
('SKUpuyol007','todo-futbol'),
('SKUpuyol007','todo-hombre'),
('SKUpuyol007','todo-mujer'),
('SKUpuyol007','todo-deporte'),
('SKUj.alvarez008','todo-futbol'),
('SKUj.alvarez008','todo-hombre'),
('SKUj.alvarez008','todo-mujer'),
('SKUj.alvarez008','todo-deporte'),
('SKUregatepro009','todo-futbol'),
('SKUregatepro009','todo-hombre'),
('SKUregatepro009','todo-mujer'),
('SKUregatepro009','todo-deporte'),
('SKUtirogol010','todo-futbol'),
('SKUtirogol010','todo-hombre'),
('SKUtirogol010','todo-mujer'),
('SKUtirogol010','todo-deporte'),
('SKUvueloportero011','todo-futbol'),
('SKUvueloportero011','todo-hombre'),
('SKUvueloportero011','todo-mujer'),
('SKUvueloportero011','todo-deporte'),
('SKUcristianoronaldo020','todo-futbol'),
('SKUcristianoronaldo020','todo-hombre'),
('SKUcristianoronaldo020','todo-mujer'),
('SKUcristianoronaldo020','todo-deporte'),
('SKUmessi021','todo-futbol'),
('SKUmessi021','todo-hombre'),
('SKUmessi021','todo-mujer'),
('SKUmessi021','todo-deporte'),
('SKUcopamundial022','todo-futbol'),
('SKUcopamundial022','todo-hombre'),
('SKUcopamundial022','todo-mujer'),
('SKUcopamundial022','todo-deporte'),
('SKUbalondefutbol031','todo-futbol'),
('SKUbalondefutbol031','todo-hombre'),
('SKUbalondefutbol031','todo-mujer'),
('SKUbalondefutbol031','todo-deporte'),
('SKUaraña001','todo-halloween'),
('SKUaraña001','todo-miedo'),
('SKUaraña001','todo-celebracion'),
('SKUvampiresa002','todo-halloween'),
('SKUvampiresa002','todo-miedo'),
('SKUvampiresa002','todo-celebracion'),
('SKUcalabazahalloween003','todo-halloween'),
('SKUcalabazahalloween003','todo-miedo'),
('SKUcalabazahalloween003','todo-celebracion'),
('SKUcalabaza004','todo-halloween'),
('SKUcalabaza004','todo-miedo'),
('SKUcalabaza004','todo-celebracion'),
('SKUcalaberagirl005','todo-halloween'),
('SKUcalaberagirl005','todo-miedo'),
('SKUcalaberagirl005','todo-celebracion'),
('SKUcalabera006','todo-halloween'),
('SKUcalabera006','todo-miedo'),
('SKUcalabera006','todo-celebracion'),
('SKUcatrina007','todo-halloween'),
('SKUcatrina007','todo-miedo'),
('SKUcatrina007','todo-celebracion'),
('SKUdulcehalloween008','todo-halloween'),
('SKUdulcehalloween008','todo-miedo'),
('SKUdulcehalloween008','todo-celebracion'),
('SKUescobamagica009','todo-halloween'),
('SKUescobamagica009','todo-miedo'),
('SKUescobamagica009','todo-celebracion'),
('SKUesqueletoide010','todo-halloween'),
('SKUesqueletoide010','todo-miedo'),
('SKUesqueletoide010','todo-celebracion'),
('SKUfrankuadrado011','todo-halloween'),
('SKUfrankuadrado011','todo-miedo'),
('SKUfrankuadrado011','todo-celebracion'),
('SKUsombrerodebruja012','todo-halloween'),
('SKUsombrerodebruja012','todo-miedo'),
('SKUsombrerodebruja012','todo-celebracion'),
('SKUojoterror013','todo-halloween'),
('SKUojoterror013','todo-miedo'),
('SKUojoterror013','todo-celebracion'),
('SKUcalderodebruja014','todo-halloween'),
('SKUcalderodebruja014','todo-miedo'),
('SKUcalderodebruja014','todo-celebracion'),
('SKUoogieboogie015','todo-halloween'),
('SKUoogieboogie015','todo-miedo'),
('SKUoogieboogie015','todo-celebracion'),
('SKUr.i.p.016','todo-halloween'),
('SKUr.i.p.016','todo-miedo'),
('SKUr.i.p.016','todo-celebracion'),
('SKUghostface017','todo-halloween'),
('SKUghostface017','todo-miedo'),
('SKUghostface017','todo-celebracion'),
('SKUtelarañahalloween018','todo-halloween'),
('SKUtelarañahalloween018','todo-miedo'),
('SKUtelarañahalloween018','todo-celebracion'),
('SKUfantasmin019','todo-halloween'),
('SKUfantasmin019','todo-miedo'),
('SKUfantasmin019','todo-celebracion'),
('SKUjacks.020','todo-halloween'),
('SKUjacks.020','todo-miedo'),
('SKUjacks.020','todo-celebracion'),
('SKUmurcielaguin021','todo-halloween'),
('SKUmurcielaguin021','todo-miedo'),
('SKUmurcielaguin021','todo-celebracion'),
('SKUmurcicute022','todo-halloween'),
('SKUmurcicute022','todo-miedo'),
('SKUmurcicute022','todo-celebracion'),
('SKUmarshall001','todo-pawpatrol'),
('SKUmarshall001','todo-ninos'),
('SKUmarshall001','todo-cartoon'),
('SKUchase002','todo-pawpatrol'),
('SKUchase002','todo-ninos'),
('SKUchase002','todo-cartoon'),
('SKUskye003','todo-pawpatrol'),
('SKUskye003','todo-ninos'),
('SKUskye003','todo-cartoon'),
('SKUrubble004','todo-pawpatrol'),
('SKUrubble004','todo-ninos'),
('SKUrubble004','todo-cartoon'),
('SKUmarshall2005','todo-pawpatrol'),
('SKUmarshall2005','todo-ninos'),
('SKUmarshall2005','todo-cartoon'),
('SKUhuellacachorro006','todo-pawpatrol'),
('SKUhuellacachorro006','todo-ninos'),
('SKUhuellacachorro006','todo-cartoon'),
('SKUpawpatrol007','todo-pawpatrol'),
('SKUpawpatrol007','todo-ninos'),
('SKUpawpatrol007','todo-cartoon'),
('SKUmarshall3008','todo-pawpatrol'),
('SKUmarshall3008','todo-ninos'),
('SKUmarshall3008','todo-cartoon'),
('SKUchase2009','todo-pawpatrol'),
('SKUchase2009','todo-ninos'),
('SKUchase2009','todo-cartoon'),
('SKUskye2010','todo-pawpatrol'),
('SKUskye2010','todo-ninos'),
('SKUskye2010','todo-cartoon'),
('SKUrocky011','todo-pawpatrol'),
('SKUrocky011','todo-ninos'),
('SKUrocky011','todo-cartoon'),
('SKUzuma012','todo-pawpatrol'),
('SKUzuma012','todo-ninos'),
('SKUzuma012','todo-cartoon'),
('SKUrubble2013','todo-pawpatrol'),
('SKUrubble2013','todo-ninos'),
('SKUrubble2013','todo-cartoon'),
('SKUeverest014','todo-pawpatrol'),
('SKUeverest014','todo-ninos'),
('SKUeverest014','todo-cartoon'),
('SKUryder015','todo-pawpatrol'),
('SKUryder015','todo-ninos'),
('SKUryder015','todo-cartoon'),
('SKUmystery001','todo-guerreras-kpop'),
('SKUmystery001','todo-ninos'),
('SKUmystery001','todo-netflix'),
('SKUmystery001','todo-cartoon'),
('SKUromance002','todo-guerreras-kpop'),
('SKUromance002','todo-ninos'),
('SKUromance002','todo-netflix'),
('SKUromance002','todo-cartoon'),
('SKUbaby003','todo-guerreras-kpop'),
('SKUbaby003','todo-ninos'),
('SKUbaby003','todo-netflix'),
('SKUbaby003','todo-cartoon'),
('SKUjinu004','todo-guerreras-kpop'),
('SKUjinu004','todo-ninos'),
('SKUjinu004','todo-netflix'),
('SKUjinu004','todo-cartoon'),
('SKUabby005','todo-guerreras-kpop'),
('SKUabby005','todo-ninos'),
('SKUabby005','todo-netflix'),
('SKUabby005','todo-cartoon'),
('SKUmira006','todo-guerreras-kpop'),
('SKUmira006','todo-ninos'),
('SKUmira006','todo-netflix'),
('SKUmira006','todo-cartoon'),
('SKUzoey007','todo-guerreras-kpop'),
('SKUzoey007','todo-ninos'),
('SKUzoey007','todo-netflix'),
('SKUzoey007','todo-cartoon'),
('SKUrumi008','todo-guerreras-kpop'),
('SKUrumi008','todo-ninos'),
('SKUrumi008','todo-netflix'),
('SKUrumi008','todo-cartoon'),
('SKUderpy009','todo-guerreras-kpop'),
('SKUderpy009','todo-ninos'),
('SKUderpy009','todo-netflix'),
('SKUderpy009','todo-cartoon'),
('SKUsussie010','todo-guerreras-kpop'),
('SKUsussie010','todo-ninos'),
('SKUsussie010','todo-netflix'),
('SKUsussie010','todo-cartoon'),
('SKUdemon011','todo-guerreras-kpop'),
('SKUdemon011','todo-ninos'),
('SKUdemon011','todo-netflix'),
('SKUdemon011','todo-cartoon'),
('SKUsodapop012','todo-guerreras-kpop'),
('SKUsodapop012','todo-ninos'),
('SKUsodapop012','todo-netflix'),
('SKUsodapop012','todo-cartoon'),
('SKUdemonking013','todo-guerreras-kpop'),
('SKUdemonking013','todo-ninos'),
('SKUdemonking013','todo-netflix'),
('SKUdemonking013','todo-cartoon'),
('SKUcookiepluto001','todo-postres-disney'),
('SKUcookiepluto001','todo-disney'),
('SKUcookiepluto001','todo-ninos'),
('SKUcookiepluto001','todo-cartoon'),
('SKUcookiedonald002','todo-postres-disney'),
('SKUcookiedonald002','todo-disney'),
('SKUcookiedonald002','todo-ninos'),
('SKUcookiedonald002','todo-cartoon'),
('SKUcookieminnie003','todo-postres-disney'),
('SKUcookieminnie003','todo-disney'),
('SKUcookieminnie003','todo-ninos'),
('SKUcookieminnie003','todo-cartoon'),
('SKUcookiemickey004','todo-postres-disney'),
('SKUcookiemickey004','todo-disney'),
('SKUcookiemickey004','todo-ninos'),
('SKUcookiemickey004','todo-cartoon'),
('SKUcookiegoofy005','todo-postres-disney'),
('SKUcookiegoofy005','todo-disney'),
('SKUcookiegoofy005','todo-ninos'),
('SKUcookiegoofy005','todo-cartoon'),
('SKUpaletamickey006','todo-postres-disney'),
('SKUpaletamickey006','todo-disney'),
('SKUpaletamickey006','todo-ninos'),
('SKUpaletamickey006','todo-cartoon'),
('SKUpaletawinnie007','todo-postres-disney'),
('SKUpaletawinnie007','todo-disney'),
('SKUpaletawinnie007','todo-ninos'),
('SKUpaletawinnie007','todo-cartoon'),
('SKUmuffinmouse008','todo-postres-disney'),
('SKUmuffinmouse008','todo-disney'),
('SKUmuffinmouse008','todo-ninos'),
('SKUmuffinmouse008','todo-cartoon'),
('SKUicecreamminnie009','todo-postres-disney'),
('SKUicecreamminnie009','todo-disney'),
('SKUicecreamminnie009','todo-ninos'),
('SKUicecreamminnie009','todo-cartoon'),
('SKUicecreammickey010','todo-postres-disney'),
('SKUicecreammickey010','todo-disney'),
('SKUicecreammickey010','todo-ninos'),
('SKUicecreammickey010','todo-cartoon'),
('SKUguantemm011','todo-postres-disney'),
('SKUguantemm011','todo-disney'),
('SKUguantemm011','todo-ninos'),
('SKUguantemm011','todo-cartoon'),
('SKUpantaloncillosmm012','todo-postres-disney'),
('SKUpantaloncillosmm012','todo-disney'),
('SKUpantaloncillosmm012','todo-ninos'),
('SKUpantaloncillosmm012','todo-cartoon'),
('SKUzapatosmm013','todo-postres-disney'),
('SKUzapatosmm013','todo-disney'),
('SKUzapatosmm013','todo-ninos'),
('SKUzapatosmm013','todo-cartoon'),
('SKUlistonmm014','todo-postres-disney'),
('SKUlistonmm014','todo-disney'),
('SKUlistonmm014','todo-ninos'),
('SKUlistonmm014','todo-cartoon'),
('SKUrenonavideño001','todo-navidad'),
('SKUrenonavideño001','todo-celebracion'),
('SKUcoronadenavidad002','todo-navidad'),
('SKUcoronadenavidad002','todo-celebracion'),
('SKUesferadenavidad003','todo-navidad'),
('SKUesferadenavidad003','todo-celebracion'),
('SKUdulcedenavidad004','todo-navidad'),
('SKUdulcedenavidad004','todo-celebracion'),
('SKUsantaatrapado005','todo-navidad'),
('SKUsantaatrapado005','todo-celebracion'),
('SKUhuellanavidad006','todo-navidad'),
('SKUhuellanavidad006','todo-celebracion'),
('SKUnavidadperruna007','todo-navidad'),
('SKUnavidadperruna007','todo-celebracion'),
('SKUmuñecodenavidad008','todo-navidad'),
('SKUmuñecodenavidad008','todo-celebracion'),
('SKUrodolforeno009','todo-navidad'),
('SKUrodolforeno009','todo-celebracion'),
('SKUsantaclaus010','todo-navidad'),
('SKUsantaclaus010','todo-celebracion'),
('SKUregalodenavidad011','todo-navidad'),
('SKUregalodenavidad011','todo-celebracion'),
('SKUvelanavideña012','todo-navidad'),
('SKUvelanavideña012','todo-celebracion'),
('SKUesferadenavidad2013','todo-navidad'),
('SKUesferadenavidad2013','todo-celebracion'),
('SKUmuñecodejengibre014','todo-navidad'),
('SKUmuñecodejengibre014','todo-celebracion'),
('SKUmuñecodejengibre2015','todo-navidad'),
('SKUmuñecodejengibre2015','todo-celebracion'),
('SKUarboldenavidad016','todo-navidad'),
('SKUarboldenavidad016','todo-celebracion'),
('SKUelgrinch017','todo-navidad'),
('SKUelgrinch017','todo-celebracion'),
('SKUcasadenavidad018','todo-navidad'),
('SKUcasadenavidad018','todo-celebracion'),
('SKUcoronadenavidad2019','todo-navidad'),
('SKUcoronadenavidad2019','todo-celebracion'),
('SKUkittynavideno020','todo-navidad'),
('SKUkittynavideno020','todo-celebracion'),
('SKUsnoopynavideño021','todo-navidad'),
('SKUsnoopynavideño021','todo-celebracion'),
('SKUstitchhawai001','todo-stitch'),
('SKUstitchhawai001','todo-lilo-stitch'),
('SKUstitchhawai001','todo-cartoon'),
('SKUstitchhawai001','todo-disney'),
('SKUstitchhawai001','todo-ninos'),
('SKUstitchhi002','todo-stitch'),
('SKUstitchhi002','todo-lilo-stitch'),
('SKUstitchhi002','todo-cartoon'),
('SKUstitchhi002','todo-disney'),
('SKUstitchhi002','todo-ninos'),
('SKUstitchbonito003','todo-stitch'),
('SKUstitchbonito003','todo-lilo-stitch'),
('SKUstitchbonito003','todo-cartoon'),
('SKUstitchbonito003','todo-disney'),
('SKUstitchbonito003','todo-ninos'),
('SKUangelback004','todo-stitch'),
('SKUangelback004','todo-lilo-stitch'),
('SKUangelback004','todo-cartoon'),
('SKUangelback004','todo-disney'),
('SKUangelback004','todo-ninos'),
('SKUstitchhead005','todo-stitch'),
('SKUstitchhead005','todo-lilo-stitch'),
('SKUstitchhead005','todo-cartoon'),
('SKUstitchhead005','todo-disney'),
('SKUstitchhead005','todo-ninos'),
('SKUangel006','todo-stitch'),
('SKUangel006','todo-lilo-stitch'),
('SKUangel006','todo-cartoon'),
('SKUangel006','todo-disney'),
('SKUangel006','todo-ninos'),
('SKUangelinlove007','todo-stitch'),
('SKUangelinlove007','todo-lilo-stitch'),
('SKUangelinlove007','todo-cartoon'),
('SKUangelinlove007','todo-disney'),
('SKUangelinlove007','todo-ninos'),
('SKUlilohawai008','todo-stitch'),
('SKUlilohawai008','todo-lilo-stitch'),
('SKUlilohawai008','todo-cartoon'),
('SKUlilohawai008','todo-disney'),
('SKUlilohawai008','todo-ninos'),
('SKUagentepleakley009','todo-stitch'),
('SKUagentepleakley009','todo-lilo-stitch'),
('SKUagentepleakley009','todo-cartoon'),
('SKUagentepleakley009','todo-disney'),
('SKUagentepleakley009','todo-ninos'),
('SKUjumbajookiba010','todo-stitch'),
('SKUjumbajookiba010','todo-lilo-stitch'),
('SKUjumbajookiba010','todo-cartoon'),
('SKUjumbajookiba010','todo-disney'),
('SKUjumbajookiba010','todo-ninos'),
('SKUstitch011','todo-stitch'),
('SKUstitch011','todo-lilo-stitch'),
('SKUstitch011','todo-cartoon'),
('SKUstitch011','todo-disney'),
('SKUstitch011','todo-ninos'),
('SKUtabladesurf012','todo-stitch'),
('SKUtabladesurf012','todo-lilo-stitch'),
('SKUtabladesurf012','todo-cartoon'),
('SKUtabladesurf012','todo-disney'),
('SKUtabladesurf012','todo-ninos'),
('SKUpiñahawai013','todo-stitch'),
('SKUpiñahawai013','todo-lilo-stitch'),
('SKUpiñahawai013','todo-cartoon'),
('SKUpiñahawai013','todo-disney'),
('SKUpiñahawai013','todo-ninos'),
('SKUarmaespacial014','todo-stitch'),
('SKUarmaespacial014','todo-lilo-stitch'),
('SKUarmaespacial014','todo-cartoon'),
('SKUarmaespacial014','todo-disney'),
('SKUarmaespacial014','todo-ninos'),
('SKUlilo015','todo-stitch'),
('SKUlilo015','todo-lilo-stitch'),
('SKUlilo015','todo-cartoon'),
('SKUlilo015','todo-disney'),
('SKUlilo015','todo-ninos'),
('SKUbabero001','todo-bebes'),
('SKUbabero001','todo-baby-shower'),
('SKUbabero001','todo-ninos'),
('SKUbabero001','todo-celebracion'),
('SKUbiberon002','todo-bebes'),
('SKUbiberon002','todo-baby-shower'),
('SKUbiberon002','todo-ninos'),
('SKUbiberon002','todo-celebracion'),
('SKUchupete003','todo-bebes'),
('SKUchupete003','todo-baby-shower'),
('SKUchupete003','todo-ninos'),
('SKUchupete003','todo-celebracion'),
('SKUpiecito004','todo-bebes'),
('SKUpiecito004','todo-baby-shower'),
('SKUpiecito004','todo-ninos'),
('SKUpiecito004','todo-celebracion'),
('SKUtestpositivo005','todo-bebes'),
('SKUtestpositivo005','todo-baby-shower'),
('SKUtestpositivo005','todo-ninos'),
('SKUtestpositivo005','todo-celebracion'),
('SKUnene006','todo-bebes'),
('SKUnene006','todo-baby-shower'),
('SKUnene006','todo-ninos'),
('SKUnene006','todo-celebracion'),
('SKUnena007','todo-bebes'),
('SKUnena007','todo-baby-shower'),
('SKUnena007','todo-ninos'),
('SKUnena007','todo-celebracion'),
('SKUenteritoazul008','todo-bebes'),
('SKUenteritoazul008','todo-baby-shower'),
('SKUenteritoazul008','todo-ninos'),
('SKUenteritoazul008','todo-celebracion'),
('SKUcascabel009','todo-bebes'),
('SKUcascabel009','todo-baby-shower'),
('SKUcascabel009','todo-ninos'),
('SKUcascabel009','todo-celebracion'),
('SKUchupete2010','todo-bebes'),
('SKUchupete2010','todo-baby-shower'),
('SKUchupete2010','todo-ninos'),
('SKUchupete2010','todo-celebracion'),
('SKUcigüeña011','todo-bebes'),
('SKUcigüeña011','todo-baby-shower'),
('SKUcigüeña011','todo-ninos'),
('SKUcigüeña011','todo-celebracion'),
('SKUcoche012','todo-bebes'),
('SKUcoche012','todo-baby-shower'),
('SKUcoche012','todo-ninos'),
('SKUcoche012','todo-celebracion'),
('SKUgorrolana013','todo-bebes'),
('SKUgorrolana013','todo-baby-shower'),
('SKUgorrolana013','todo-ninos'),
('SKUgorrolana013','todo-celebracion'),
('SKUfuturamamá014','todo-bebes'),
('SKUfuturamamá014','todo-baby-shower'),
('SKUfuturamamá014','todo-ninos'),
('SKUfuturamamá014','todo-celebracion'),
('SKUositorosa015','todo-bebes'),
('SKUositorosa015','todo-baby-shower'),
('SKUositorosa015','todo-ninos'),
('SKUositorosa015','todo-celebracion'),
('SKUpatodehule016','todo-bebes'),
('SKUpatodehule016','todo-baby-shower'),
('SKUpatodehule016','todo-ninos'),
('SKUpatodehule016','todo-celebracion'),
('SKUpañal017','todo-bebes'),
('SKUpañal017','todo-baby-shower'),
('SKUpañal017','todo-ninos'),
('SKUpañal017','todo-celebracion'),
('SKUbiberon2018','todo-bebes'),
('SKUbiberon2018','todo-baby-shower'),
('SKUbiberon2018','todo-ninos'),
('SKUbiberon2018','todo-celebracion'),
('SKUhadagatina001','todo-la-casa-de-gabby'),
('SKUhadagatina001','todo-cartoon'),
('SKUhadagatina001','todo-ninos'),
('SKUhadagatina001','todo-netflix'),
('SKUpastelillo002','todo-la-casa-de-gabby'),
('SKUpastelillo002','todo-cartoon'),
('SKUpastelillo002','todo-ninos'),
('SKUpastelillo002','todo-netflix'),
('SKUpandypatas003','todo-la-casa-de-gabby'),
('SKUpandypatas003','todo-cartoon'),
('SKUpandypatas003','todo-ninos'),
('SKUpandypatas003','todo-netflix'),
('SKUgabby004','todo-la-casa-de-gabby'),
('SKUgabby004','todo-cartoon'),
('SKUgabby004','todo-ninos'),
('SKUgabby004','todo-netflix'),
('SKUsiregata005','todo-la-casa-de-gabby'),
('SKUsiregata005','todo-cartoon'),
('SKUsiregata005','todo-ninos'),
('SKUsiregata005','todo-netflix'),
('SKUdjcapucha006','todo-la-casa-de-gabby'),
('SKUdjcapucha006','todo-cartoon'),
('SKUdjcapucha006','todo-ninos'),
('SKUdjcapucha006','todo-netflix'),
('SKUbebécaja007','todo-la-casa-de-gabby'),
('SKUbebécaja007','todo-cartoon'),
('SKUbebécaja007','todo-ninos'),
('SKUbebécaja007','todo-netflix'),
('SKUescurrigato008','todo-la-casa-de-gabby'),
('SKUescurrigato008','todo-cartoon'),
('SKUescurrigato008','todo-ninos'),
('SKUescurrigato008','todo-netflix'),
('SKUwinnie001','todo-winie-the-pooh'),
('SKUwinnie001','todo-cartoon'),
('SKUwinnie001','todo-ninos'),
('SKUwinnie001','todo-disney'),
('SKUtigger002','todo-winie-the-pooh'),
('SKUtigger002','todo-cartoon'),
('SKUtigger002','todo-ninos'),
('SKUtigger002','todo-disney'),
('SKUpiglet003','todo-winie-the-pooh'),
('SKUpiglet003','todo-cartoon'),
('SKUpiglet003','todo-ninos'),
('SKUpiglet003','todo-disney'),
('SKUhunny004','todo-winie-the-pooh'),
('SKUhunny004','todo-cartoon'),
('SKUhunny004','todo-ninos'),
('SKUhunny004','todo-disney'),
('SKUwinniefeliz005','todo-winie-the-pooh'),
('SKUwinniefeliz005','todo-cartoon'),
('SKUwinniefeliz005','todo-ninos'),
('SKUwinniefeliz005','todo-disney'),
('SKUwinnieglobos006','todo-winie-the-pooh'),
('SKUwinnieglobos006','todo-cartoon'),
('SKUwinnieglobos006','todo-ninos'),
('SKUwinnieglobos006','todo-disney'),
('SKUpiglet2007','todo-winie-the-pooh'),
('SKUpiglet2007','todo-cartoon'),
('SKUpiglet2007','todo-ninos'),
('SKUpiglet2007','todo-disney'),
('SKUtigger2009','todo-winie-the-pooh'),
('SKUtigger2009','todo-cartoon'),
('SKUtigger2009','todo-ninos'),
('SKUtigger2009','todo-disney'),
('SKUwinniecurioso010','todo-winie-the-pooh'),
('SKUwinniecurioso010','todo-cartoon'),
('SKUwinniecurioso010','todo-ninos'),
('SKUwinniecurioso010','todo-disney'),
('SKUhamm001','todo-toystory'),
('SKUhamm001','todo-cartoon'),
('SKUhamm001','todo-netflix'),
('SKUhamm001','todo-disney'),
('SKUhamm001','todo-ninos'),
('SKUbuzz002','todo-toystory'),
('SKUbuzz002','todo-cartoon'),
('SKUbuzz002','todo-netflix'),
('SKUbuzz002','todo-disney'),
('SKUbuzz002','todo-ninos'),
('SKUwoody003','todo-toystory'),
('SKUwoody003','todo-cartoon'),
('SKUwoody003','todo-netflix'),
('SKUwoody003','todo-disney'),
('SKUwoody003','todo-ninos'),
('SKUslinky004','todo-toystory'),
('SKUslinky004','todo-cartoon'),
('SKUslinky004','todo-netflix'),
('SKUslinky004','todo-disney'),
('SKUslinky004','todo-ninos'),
('SKUduke005','todo-toystory'),
('SKUduke005','todo-cartoon'),
('SKUduke005','todo-netflix'),
('SKUduke005','todo-disney'),
('SKUduke005','todo-ninos'),
('SKUjessie006','todo-toystory'),
('SKUjessie006','todo-cartoon'),
('SKUjessie006','todo-netflix'),
('SKUjessie006','todo-disney'),
('SKUjessie006','todo-ninos'),
('SKUrex007','todo-toystory'),
('SKUrex007','todo-cartoon'),
('SKUrex007','todo-netflix'),
('SKUrex007','todo-disney'),
('SKUrex007','todo-ninos'),
('SKUforky008','todo-toystory'),
('SKUforky008','todo-cartoon'),
('SKUforky008','todo-netflix'),
('SKUforky008','todo-disney'),
('SKUforky008','todo-ninos'),
('SKUzurg009','todo-toystory'),
('SKUzurg009','todo-cartoon'),
('SKUzurg009','todo-netflix'),
('SKUzurg009','todo-disney'),
('SKUzurg009','todo-ninos'),
('SKUbetty010','todo-toystory'),
('SKUbetty010','todo-cartoon'),
('SKUbetty010','todo-netflix'),
('SKUbetty010','todo-disney'),
('SKUbetty010','todo-ninos'),
('SKUmarcianito011','todo-toystory'),
('SKUmarcianito011','todo-cartoon'),
('SKUmarcianito011','todo-netflix'),
('SKUmarcianito011','todo-disney'),
('SKUmarcianito011','todo-ninos'),
('SKUsrcaradepapa012','todo-toystory'),
('SKUsrcaradepapa012','todo-cartoon'),
('SKUsrcaradepapa012','todo-netflix'),
('SKUsrcaradepapa012','todo-disney'),
('SKUsrcaradepapa012','todo-ninos'),
('SKUlilypad013','todo-toystory'),
('SKUlilypad013','todo-cartoon'),
('SKUlilypad013','todo-netflix'),
('SKUlilypad013','todo-disney'),
('SKUlilypad013','todo-ninos'),
('SKUpelotats014','todo-toystory'),
('SKUpelotats014','todo-cartoon'),
('SKUpelotats014','todo-netflix'),
('SKUpelotats014','todo-disney'),
('SKUpelotats014','todo-ninos'),
('SKUbuzzdeandy015','todo-toystory'),
('SKUbuzzdeandy015','todo-cartoon'),
('SKUbuzzdeandy015','todo-netflix'),
('SKUbuzzdeandy015','todo-disney'),
('SKUbuzzdeandy015','todo-ninos'),
('SKUwoodydeandy016','todo-toystory'),
('SKUwoodydeandy016','todo-cartoon'),
('SKUwoodydeandy016','todo-netflix'),
('SKUwoodydeandy016','todo-disney'),
('SKUwoodydeandy016','todo-ninos'),
('SKUsnoopy001','todo-snoopy'),
('SKUsnoopy001','todo-cartoon'),
('SKUsnoopy001','todo-ninos'),
('SKUwoodstock002','todo-snoopy'),
('SKUwoodstock002','todo-cartoon'),
('SKUwoodstock002','todo-ninos'),
('SKUcharliebrown003','todo-snoopy'),
('SKUcharliebrown003','todo-cartoon'),
('SKUcharliebrown003','todo-ninos'),
('SKUsnoopychill004','todo-snoopy'),
('SKUsnoopychill004','todo-cartoon'),
('SKUsnoopychill004','todo-ninos'),
('SKUsallybrown005','todo-snoopy'),
('SKUsallybrown005','todo-cartoon'),
('SKUsallybrown005','todo-ninos'),
('SKUlucyvanpelt006','todo-snoopy'),
('SKUlucyvanpelt006','todo-cartoon'),
('SKUlucyvanpelt006','todo-ninos'),
('SKUarenita001','todo-bob-esponja'),
('SKUarenita001','todo-cartoon'),
('SKUarenita001','todo-ninos'),
('SKUbobesponja002','todo-bob-esponja'),
('SKUbobesponja002','todo-cartoon'),
('SKUbobesponja002','todo-ninos'),
('SKUcalamardo003','todo-bob-esponja'),
('SKUcalamardo003','todo-cartoon'),
('SKUcalamardo003','todo-ninos'),
('SKUgary004','todo-bob-esponja'),
('SKUgary004','todo-cartoon'),
('SKUgary004','todo-ninos'),
('SKUmedusa005','todo-bob-esponja'),
('SKUmedusa005','todo-cartoon'),
('SKUmedusa005','todo-ninos'),
('SKUpatricio006','todo-bob-esponja'),
('SKUpatricio006','todo-cartoon'),
('SKUpatricio006','todo-ninos'),
('SKUpiñabajodelmar007','todo-bob-esponja'),
('SKUpiñabajodelmar007','todo-cartoon'),
('SKUpiñabajodelmar007','todo-ninos'),
('SKUplanton008','todo-bob-esponja'),
('SKUplanton008','todo-cartoon'),
('SKUplanton008','todo-ninos'),
('SKUabejitababy001','todo-animalitos'),
('SKUabejitababy001','todo-ninos'),
('SKUabejitababy001','todo-animales'),
('SKUburritobaby002','todo-animalitos'),
('SKUburritobaby002','todo-ninos'),
('SKUburritobaby002','todo-animales'),
('SKUcebritababy003','todo-animalitos'),
('SKUcebritababy003','todo-ninos'),
('SKUcebritababy003','todo-animales'),
('SKUcerditobaby004','todo-animalitos'),
('SKUcerditobaby004','todo-ninos'),
('SKUcerditobaby004','todo-animales'),
('SKUconejutobaby005','todo-animalitos'),
('SKUconejutobaby005','todo-ninos'),
('SKUconejutobaby005','todo-animales'),
('SKUdinobaby006','todo-animalitos'),
('SKUdinobaby006','todo-ninos'),
('SKUdinobaby006','todo-animales'),
('SKUelefantitobaby007','todo-animalitos'),
('SKUelefantitobaby007','todo-ninos'),
('SKUelefantitobaby007','todo-animales'),
('SKUpuequitoespinbaby008','todo-animalitos'),
('SKUpuequitoespinbaby008','todo-ninos'),
('SKUpuequitoespinbaby008','todo-animales'),
('SKUgatitobaby009','todo-animalitos'),
('SKUgatitobaby009','todo-ninos'),
('SKUgatitobaby009','todo-animales'),
('SKUjirafitababy010','todo-animalitos'),
('SKUjirafitababy010','todo-ninos'),
('SKUjirafitababy010','todo-animales'),
('SKUtigrirobaby011','todo-animalitos'),
('SKUtigrirobaby011','todo-ninos'),
('SKUtigrirobaby011','todo-animales'),
('SKUleoncitobaby012','todo-animalitos'),
('SKUleoncitobaby012','todo-ninos'),
('SKUleoncitobaby012','todo-animales'),
('SKUllamitababy013','todo-animalitos'),
('SKUllamitababy013','todo-ninos'),
('SKUllamitababy013','todo-animales'),
('SKUmonitobaby014','todo-animalitos'),
('SKUmonitobaby014','todo-ninos'),
('SKUmonitobaby014','todo-animales'),
('SKUpanditababy015','todo-animalitos'),
('SKUpanditababy015','todo-ninos'),
('SKUpanditababy015','todo-animales'),
('SKUpatitobaby016','todo-animalitos'),
('SKUpatitobaby016','todo-ninos'),
('SKUpatitobaby016','todo-animales'),
('SKUpingüinitobaby017','todo-animalitos'),
('SKUpingüinitobaby017','todo-ninos'),
('SKUpingüinitobaby017','todo-animales'),
('SKUserpientinbaby018','todo-animalitos'),
('SKUserpientinbaby018','todo-ninos'),
('SKUserpientinbaby018','todo-animales'),
('SKUvaquitababy019','todo-animalitos'),
('SKUvaquitababy019','todo-ninos'),
('SKUvaquitababy019','todo-animales'),
('SKUzorritobaby020','todo-animalitos'),
('SKUzorritobaby020','todo-ninos'),
('SKUzorritobaby020','todo-animales'),
('SKUcopihue001','todo-fiestas-patrias'),
('SKUcopihue001','todo-chile'),
('SKUcopihue001','todo-celebracion'),
('SKUvolantin002','todo-fiestas-patrias'),
('SKUvolantin002','todo-chile'),
('SKUvolantin002','todo-celebracion'),
('SKUbanderitachilena003','todo-fiestas-patrias'),
('SKUbanderitachilena003','todo-chile'),
('SKUbanderitachilena003','todo-celebracion'),
('SKUempanadachilena004','todo-fiestas-patrias'),
('SKUempanadachilena004','todo-chile'),
('SKUempanadachilena004','todo-celebracion'),
('SKUempanadafeliz005','todo-fiestas-patrias'),
('SKUempanadafeliz005','todo-chile'),
('SKUempanadafeliz005','todo-celebracion'),
('SKUterremotochileno006','todo-fiestas-patrias'),
('SKUterremotochileno006','todo-chile'),
('SKUterremotochileno006','todo-celebracion'),
('SKUescudochileno007','todo-fiestas-patrias'),
('SKUescudochileno007','todo-chile'),
('SKUescudochileno007','todo-celebracion'),
('SKUcircochileno008','todo-fiestas-patrias'),
('SKUcircochileno008','todo-chile'),
('SKUcircochileno008','todo-celebracion'),
('SKUcorazonchileno009','todo-fiestas-patrias'),
('SKUcorazonchileno009','todo-chile'),
('SKUcorazonchileno009','todo-celebracion'),
('SKUchoripan010','todo-fiestas-patrias'),
('SKUchoripan010','todo-chile'),
('SKUchoripan010','todo-celebracion'),
('SKUyoyo011','todo-fiestas-patrias'),
('SKUyoyo011','todo-chile'),
('SKUyoyo011','todo-celebracion'),
('SKUtrompochileno012','todo-fiestas-patrias'),
('SKUtrompochileno012','todo-chile'),
('SKUtrompochileno012','todo-celebracion')
)
insert into public.product_categories (product_id,category_id)
select p.id,c.id from links l join public.products p on p.sku=l.sku join public.categories c on c.slug=l.category_slug
on conflict do nothing;
